; ModuleID = '../bc_files/armlink_symbol_steering.bc'
source_filename = "/home/sri/zephyrproject/zephyr/build/zephyr/armlink_symbol_steering.c"
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-arm-none-eabi"

@"Image$$rom_start_0$$Base" = external dso_local global [0 x i8], align 1
@"Image$$rom_start_0$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$rom_start$$Base" = external dso_local global [0 x i8], align 1
@"Image$$rom_start$$Length" = external dso_local global [0 x i8], align 1
@"Load$$rom_start$$Base" = external dso_local global [0 x i8], align 1
@"Image$$rom_start$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$text$$Base" = external dso_local global [0 x i8], align 1
@"Image$$text$$Length" = external dso_local global [0 x i8], align 1
@"Load$$text$$Base" = external dso_local global [0 x i8], align 1
@"Image$$text$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$init_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init_102$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init_104$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init_106$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init_108$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init_110$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init$$Length" = external dso_local global [0 x i8], align 1
@"Load$$init$$Base" = external dso_local global [0 x i8], align 1
@"Image$$init_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$device_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$device_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$device_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$device_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$device_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$device_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$sw_isr_table$$Base" = external dso_local global [0 x i8], align 1
@"Image$$sw_isr_table$$Length" = external dso_local global [0 x i8], align 1
@"Load$$sw_isr_table$$Base" = external dso_local global [0 x i8], align 1
@"Image$$sw_isr_table$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$initlevel_error$$Base" = external dso_local global [0 x i8], align 1
@"Image$$initlevel_error$$Length" = external dso_local global [0 x i8], align 1
@"Load$$initlevel_error$$Base" = external dso_local global [0 x i8], align 1
@"Image$$initlevel_error_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$app_shmem_regions$$Base" = external dso_local global [0 x i8], align 1
@"Image$$app_shmem_regions$$Length" = external dso_local global [0 x i8], align 1
@"Load$$app_shmem_regions$$Base" = external dso_local global [0 x i8], align 1
@"Image$$app_shmem_regions_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$bt_l2cap_fixed_chan_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bt_l2cap_fixed_chan_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$bt_l2cap_fixed_chan_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bt_l2cap_fixed_chan_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$bt_l2cap_fixed_chan_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bt_l2cap_fixed_chan_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$bt_gatt_service_static_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bt_gatt_service_static_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$bt_gatt_service_static_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bt_gatt_service_static_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$bt_gatt_service_static_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bt_gatt_service_static_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_p4wq_initparam_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_p4wq_initparam_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_p4wq_initparam_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_p4wq_initparam_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_p4wq_initparam_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_p4wq_initparam_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$log_strings_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_strings_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$log_strings_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_strings_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$log_strings_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_strings_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$log_const_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_const_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$log_const_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_const_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$log_const_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_const_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$shell_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_root_cmds_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_root_cmds_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_root_cmds_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_root_cmds_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$shell_root_cmds_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_root_cmds_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_subcmds_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_subcmds_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_subcmds_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_subcmds_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$shell_subcmds_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_subcmds_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_dynamic_subcmds_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_dynamic_subcmds_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$shell_dynamic_subcmds_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_dynamic_subcmds_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$shell_dynamic_subcmds_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$shell_dynamic_subcmds_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$cfb_font_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$cfb_font_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$cfb_font_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$cfb_font_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$cfb_font_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$cfb_font_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$tracing_backend_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$tracing_backend_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$tracing_backend_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$tracing_backend_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$tracing_backend_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$tracing_backend_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$zephyr_dbg_info$$Base" = external dso_local global [0 x i8], align 1
@"Image$$zephyr_dbg_info$$Length" = external dso_local global [0 x i8], align 1
@"Load$$zephyr_dbg_info$$Base" = external dso_local global [0 x i8], align 1
@"Image$$zephyr_dbg_info$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$_static_thread_data_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$_static_thread_data_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$_static_thread_data_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$_static_thread_data_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$_static_thread_data_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$_static_thread_data_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$rodata$$Base" = external dso_local global [0 x i8], align 1
@"Image$$rodata$$Length" = external dso_local global [0 x i8], align 1
@"Load$$rodata$$Base" = external dso_local global [0 x i8], align 1
@"Image$$rodata$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$ARM_exidx$$Base" = external dso_local global [0 x i8], align 1
@"Image$$ARM_exidx$$Length" = external dso_local global [0 x i8], align 1
@"Load$$ARM_exidx$$Base" = external dso_local global [0 x i8], align 1
@"Image$$ARM_exidx$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$data$$Base" = external dso_local global [0 x i8], align 1
@"Image$$data$$Length" = external dso_local global [0 x i8], align 1
@"Load$$data$$Base" = external dso_local global [0 x i8], align 1
@"Image$$data$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$device_states$$Base" = external dso_local global [0 x i8], align 1
@"Image$$device_states$$Length" = external dso_local global [0 x i8], align 1
@"Load$$device_states$$Base" = external dso_local global [0 x i8], align 1
@"Image$$device_states$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$log_dynamic_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_dynamic_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$log_dynamic_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_dynamic_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$log_dynamic_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$log_dynamic_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_timer_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_timer_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_timer_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_timer_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_timer_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_timer_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_mem_slab_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mem_slab_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_mem_slab_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mem_slab_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_mem_slab_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mem_slab_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_heap_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_heap_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_heap_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_heap_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_heap_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_heap_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_mutex_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mutex_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_mutex_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mutex_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_mutex_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mutex_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_stack_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_stack_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_stack_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_stack_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_stack_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_stack_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_msgq_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_msgq_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_msgq_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_msgq_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_msgq_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_msgq_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_mbox_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mbox_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_mbox_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mbox_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_mbox_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_mbox_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_pipe_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_pipe_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_pipe_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_pipe_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_pipe_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_pipe_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_sem_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_sem_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_sem_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_sem_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_sem_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_sem_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_queue_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_queue_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_queue_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_queue_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_queue_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_queue_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_condvar_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_condvar_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_condvar_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_condvar_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_condvar_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_condvar_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_event_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_event_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$k_event_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_event_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$k_event_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$k_event_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$net_buf_pool_area_100$$Base" = external dso_local global [0 x i8], align 1
@"Image$$net_buf_pool_area_100$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$net_buf_pool_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$net_buf_pool_area$$Length" = external dso_local global [0 x i8], align 1
@"Load$$net_buf_pool_area$$Base" = external dso_local global [0 x i8], align 1
@"Image$$net_buf_pool_area_end$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$ramfunc$$Base" = external dso_local global [0 x i8], align 1
@"Image$$ramfunc$$Length" = external dso_local global [0 x i8], align 1
@"Load$$ramfunc$$Base" = external dso_local global [0 x i8], align 1
@"Image$$ramfunc$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$noinit$$Base" = external dso_local global [0 x i8], align 1
@"Image$$noinit$$Length" = external dso_local global [0 x i8], align 1
@"Load$$noinit$$Base" = external dso_local global [0 x i8], align 1
@"Image$$noinit$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$bss$$ZI$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bss$$ZI$$Length" = external dso_local global [0 x i8], align 1
@"Load$$bss$$ZI$$Base" = external dso_local global [0 x i8], align 1
@"Image$$bss$$ZI$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$last_ram_section$$ZI$$Base" = external dso_local global [0 x i8], align 1
@"Image$$last_ram_section$$ZI$$Length" = external dso_local global [0 x i8], align 1
@"Load$$last_ram_section$$ZI$$Base" = external dso_local global [0 x i8], align 1
@"Image$$last_ram_section$$ZI$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$net_buf_pool_area$$Limit" = external dso_local global [0 x i8], align 1
@"Image$$__kernel_ram_start$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__kernel_ram_end$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__kernel_ram_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$_image_ram_start$$Base" = external dso_local global [0 x i8], align 1
@"Image$$ARM_LIB_STACKHEAP$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__init_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__device_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__initlevel_error_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__app_shmem_regions_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__bt_l2cap_fixed_chan_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__bt_gatt_service_static_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_p4wq_initparam_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__log_strings_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__log_const_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__shell_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__shell_root_cmds_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__shell_subcmds_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__shell_dynamic_subcmds_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__cfb_font_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__tracing_backend_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$___static_thread_data_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__log_dynamic_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_timer_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_mem_slab_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_heap_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_mutex_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_stack_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_msgq_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_mbox_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_pipe_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_sem_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_queue_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_condvar_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__k_event_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__net_buf_pool_area_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__rom_region_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__text_region_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__rodata_region_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__ram_region_size$$Base" = external dso_local global [0 x i8], align 1
@"Image$$__data_region_size$$Base" = external dso_local global [0 x i8], align 1

; Function Attrs: nounwind optsize
define hidden i32 @__armlink_symbol_steering() #0 !dbg !11 {
  ret i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 and (i32 ptrtoint (ptr @"Image$$rom_start_0$$Base" to i32), i32 ptrtoint (ptr @"Image$$rom_start_0$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$rom_start$$Base" to i32)), i32 ptrtoint (ptr @"Image$$rom_start$$Length" to i32)), i32 ptrtoint (ptr @"Load$$rom_start$$Base" to i32)), i32 ptrtoint (ptr @"Image$$rom_start$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$text$$Base" to i32)), i32 ptrtoint (ptr @"Image$$text$$Length" to i32)), i32 ptrtoint (ptr @"Load$$text$$Base" to i32)), i32 ptrtoint (ptr @"Image$$text$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$init_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init_102$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init_104$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init_106$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init_108$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init_110$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init$$Length" to i32)), i32 ptrtoint (ptr @"Load$$init$$Base" to i32)), i32 ptrtoint (ptr @"Image$$init_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$device_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$device_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$device_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$device_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$device_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$device_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$sw_isr_table$$Base" to i32)), i32 ptrtoint (ptr @"Image$$sw_isr_table$$Length" to i32)), i32 ptrtoint (ptr @"Load$$sw_isr_table$$Base" to i32)), i32 ptrtoint (ptr @"Image$$sw_isr_table$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$initlevel_error$$Base" to i32)), i32 ptrtoint (ptr @"Image$$initlevel_error$$Length" to i32)), i32 ptrtoint (ptr @"Load$$initlevel_error$$Base" to i32)), i32 ptrtoint (ptr @"Image$$initlevel_error_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$app_shmem_regions$$Base" to i32)), i32 ptrtoint (ptr @"Image$$app_shmem_regions$$Length" to i32)), i32 ptrtoint (ptr @"Load$$app_shmem_regions$$Base" to i32)), i32 ptrtoint (ptr @"Image$$app_shmem_regions_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$bt_l2cap_fixed_chan_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bt_l2cap_fixed_chan_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$bt_l2cap_fixed_chan_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bt_l2cap_fixed_chan_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$bt_l2cap_fixed_chan_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bt_l2cap_fixed_chan_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$bt_gatt_service_static_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bt_gatt_service_static_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$bt_gatt_service_static_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bt_gatt_service_static_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$bt_gatt_service_static_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bt_gatt_service_static_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_p4wq_initparam_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_p4wq_initparam_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_p4wq_initparam_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_p4wq_initparam_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_p4wq_initparam_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_p4wq_initparam_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$log_strings_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_strings_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$log_strings_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_strings_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$log_strings_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_strings_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$log_const_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_const_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$log_const_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_const_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$log_const_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_const_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$shell_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_root_cmds_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_root_cmds_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_root_cmds_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_root_cmds_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$shell_root_cmds_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_root_cmds_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_subcmds_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_subcmds_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_subcmds_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_subcmds_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$shell_subcmds_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_subcmds_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_dynamic_subcmds_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_dynamic_subcmds_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$shell_dynamic_subcmds_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_dynamic_subcmds_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$shell_dynamic_subcmds_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$shell_dynamic_subcmds_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$cfb_font_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$cfb_font_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$cfb_font_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$cfb_font_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$cfb_font_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$cfb_font_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$tracing_backend_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$tracing_backend_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$tracing_backend_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$tracing_backend_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$tracing_backend_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$tracing_backend_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$zephyr_dbg_info$$Base" to i32)), i32 ptrtoint (ptr @"Image$$zephyr_dbg_info$$Length" to i32)), i32 ptrtoint (ptr @"Load$$zephyr_dbg_info$$Base" to i32)), i32 ptrtoint (ptr @"Image$$zephyr_dbg_info$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$_static_thread_data_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$_static_thread_data_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$_static_thread_data_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$_static_thread_data_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$_static_thread_data_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$_static_thread_data_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$rodata$$Base" to i32)), i32 ptrtoint (ptr @"Image$$rodata$$Length" to i32)), i32 ptrtoint (ptr @"Load$$rodata$$Base" to i32)), i32 ptrtoint (ptr @"Image$$rodata$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$ARM_exidx$$Base" to i32)), i32 ptrtoint (ptr @"Image$$ARM_exidx$$Length" to i32)), i32 ptrtoint (ptr @"Load$$ARM_exidx$$Base" to i32)), i32 ptrtoint (ptr @"Image$$ARM_exidx$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$data$$Base" to i32)), i32 ptrtoint (ptr @"Image$$data$$Length" to i32)), i32 ptrtoint (ptr @"Load$$data$$Base" to i32)), i32 ptrtoint (ptr @"Image$$data$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$device_states$$Base" to i32)), i32 ptrtoint (ptr @"Image$$device_states$$Length" to i32)), i32 ptrtoint (ptr @"Load$$device_states$$Base" to i32)), i32 ptrtoint (ptr @"Image$$device_states$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$log_dynamic_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_dynamic_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$log_dynamic_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_dynamic_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$log_dynamic_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$log_dynamic_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_timer_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_timer_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_timer_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_timer_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_timer_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_timer_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_mem_slab_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mem_slab_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_mem_slab_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mem_slab_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_mem_slab_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mem_slab_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_heap_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_heap_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_heap_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_heap_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_heap_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_heap_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_mutex_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mutex_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_mutex_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mutex_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_mutex_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mutex_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_stack_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_stack_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_stack_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_stack_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_stack_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_stack_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_msgq_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_msgq_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_msgq_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_msgq_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_msgq_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_msgq_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_mbox_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mbox_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_mbox_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mbox_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_mbox_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_mbox_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_pipe_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_pipe_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_pipe_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_pipe_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_pipe_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_pipe_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_sem_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_sem_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_sem_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_sem_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_sem_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_sem_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_queue_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_queue_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_queue_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_queue_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_queue_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_queue_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_condvar_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_condvar_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_condvar_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_condvar_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_condvar_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_condvar_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_event_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_event_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$k_event_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_event_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$k_event_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$k_event_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$net_buf_pool_area_100$$Base" to i32)), i32 ptrtoint (ptr @"Image$$net_buf_pool_area_100$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$net_buf_pool_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$net_buf_pool_area$$Length" to i32)), i32 ptrtoint (ptr @"Load$$net_buf_pool_area$$Base" to i32)), i32 ptrtoint (ptr @"Image$$net_buf_pool_area_end$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$ramfunc$$Base" to i32)), i32 ptrtoint (ptr @"Image$$ramfunc$$Length" to i32)), i32 ptrtoint (ptr @"Load$$ramfunc$$Base" to i32)), i32 ptrtoint (ptr @"Image$$ramfunc$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$noinit$$Base" to i32)), i32 ptrtoint (ptr @"Image$$noinit$$Length" to i32)), i32 ptrtoint (ptr @"Load$$noinit$$Base" to i32)), i32 ptrtoint (ptr @"Image$$noinit$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$bss$$ZI$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bss$$ZI$$Length" to i32)), i32 ptrtoint (ptr @"Load$$bss$$ZI$$Base" to i32)), i32 ptrtoint (ptr @"Image$$bss$$ZI$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$last_ram_section$$ZI$$Base" to i32)), i32 ptrtoint (ptr @"Image$$last_ram_section$$ZI$$Length" to i32)), i32 ptrtoint (ptr @"Load$$last_ram_section$$ZI$$Base" to i32)), i32 ptrtoint (ptr @"Image$$last_ram_section$$ZI$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$rom_start$$Base" to i32)), i32 ptrtoint (ptr @"Load$$rom_start$$Base" to i32)), i32 ptrtoint (ptr @"Image$$ARM_exidx$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$text$$Base" to i32)), i32 ptrtoint (ptr @"Load$$text$$Base" to i32)), i32 ptrtoint (ptr @"Image$$text$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$init$$Base" to i32)), i32 ptrtoint (ptr @"Load$$init$$Base" to i32)), i32 ptrtoint (ptr @"Image$$rodata$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$data$$Base" to i32)), i32 ptrtoint (ptr @"Load$$data$$Base" to i32)), i32 ptrtoint (ptr @"Image$$noinit$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$data$$Base" to i32)), i32 ptrtoint (ptr @"Load$$data$$Base" to i32)), i32 ptrtoint (ptr @"Image$$net_buf_pool_area$$Limit" to i32)), i32 ptrtoint (ptr @"Image$$__kernel_ram_start$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__kernel_ram_end$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__kernel_ram_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$_image_ram_start$$Base" to i32)), i32 ptrtoint (ptr @"Image$$ARM_LIB_STACKHEAP$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__init_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__device_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__initlevel_error_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__app_shmem_regions_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__bt_l2cap_fixed_chan_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__bt_gatt_service_static_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_p4wq_initparam_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__log_strings_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__log_const_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__shell_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__shell_root_cmds_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__shell_subcmds_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__shell_dynamic_subcmds_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__cfb_font_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__tracing_backend_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$___static_thread_data_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__log_dynamic_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_timer_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_mem_slab_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_heap_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_mutex_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_stack_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_msgq_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_mbox_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_pipe_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_sem_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_queue_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_condvar_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__k_event_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__net_buf_pool_area_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__rom_region_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__text_region_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__rodata_region_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__ram_region_size$$Base" to i32)), i32 ptrtoint (ptr @"Image$$__data_region_size$$Base" to i32)), !dbg !15
}

attributes #0 = { nounwind optsize "denormal-fp-math"="preserve-sign,preserve-sign" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cortex-m0" "target-features"="+armv6-m,+soft-float,+strict-align,+thumb-mode,-aes,-bf16,-cdecp0,-cdecp1,-cdecp2,-cdecp3,-cdecp4,-cdecp5,-cdecp6,-cdecp7,-crc,-crypto,-d32,-dotprod,-dsp,-fce,-fp-armv8,-fp-armv8d16,-fp-armv8d16sp,-fp-armv8sp,-fp16,-fp16fml,-fp64,-fpregs,-fullfp16,-hwdiv,-hwdiv-arm,-i8mm,-lob,-mve,-mve.fp,-neon,-pacbti,-ras,-sb,-sha2,-vfp2,-vfp2sp,-vfp3,-vfp3d16,-vfp3d16sp,-vfp3sp,-vfp4,-vfp4d16,-vfp4d16sp,-vfp4sp" "use-soft-float"="true" }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!4, !5, !6, !7, !8, !9}
!llvm.ident = !{!10}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "Component: Arm Compiler for Embedded 6.20 Tool: armclang [5e9ad700]", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, retainedTypes: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "armlink_symbol_steering.c", directory: "/home/sri/zephyrproject/zephyr/build")
!2 = !{!3}
!3 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!4 = !{i32 7, !"Dwarf Version", i32 4}
!5 = !{i32 2, !"Debug Info Version", i32 3}
!6 = !{i32 1, !"wchar_size", i32 4}
!7 = !{i32 1, !"static_rwdata", i32 1}
!8 = !{i32 1, !"enumsize_buildattr", i32 1}
!9 = !{i32 1, !"armlib_unavailable", i32 0}
!10 = !{!"Component: Arm Compiler for Embedded 6.20 Tool: armclang [5e9ad700]"}
!11 = distinct !DISubprogram(name: "__armlink_symbol_steering", scope: !12, file: !12, line: 290, type: !13, scopeLine: 290, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !14)
!12 = !DIFile(filename: "zephyr/armlink_symbol_steering.c", directory: "/home/sri/zephyrproject/zephyr/build")
!13 = !DISubroutineType(types: !2)
!14 = !{}
!15 = !DILocation(line: 291, column: 2, scope: !11)
