; ModuleID = 'externalLinking.c'
source_filename = "externalLinking.c"
target datalayout = "e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-pc-linux-gnu"

@__aeabi_EDOM = constant i32 33, align 4, !dbg !0
@__aeabi_ERANGE = constant i32 34, align 4, !dbg !5
@__aeabi_EILSEQ = constant i32 138, align 4, !dbg !9
@_vector_start = global i8 0, align 1, !dbg !11
@_vector_end = global i8 0, align 1, !dbg !14
@__rom_start_start = global i8 0, align 1, !dbg !16
@__rom_start_load_start = global i8 0, align 1, !dbg !18
@__rom_start_end = global i8 0, align 1, !dbg !20
@__rom_start_size = global i8 0, align 1, !dbg !22
@__text_start = global i8 0, align 1, !dbg !24
@__text_load_start = global i8 0, align 1, !dbg !26
@__text_end = global i8 0, align 1, !dbg !28
@__text_size = global i8 0, align 1, !dbg !30
@__init_EARLY_start = global i8 0, align 1, !dbg !32
@__init_PRE_KERNEL_1_start = global i8 0, align 1, !dbg !34
@__init_PRE_KERNEL_2_start = global i8 0, align 1, !dbg !36
@__init_POST_KERNEL_start = global i8 0, align 1, !dbg !38
@__init_APPLICATION_start = global i8 0, align 1, !dbg !40
@__init_SMP_start = global i8 0, align 1, !dbg !42
@__init_start = global i8 0, align 1, !dbg !44
@__init_load_start = global i8 0, align 1, !dbg !46
@_isr_wrapper = global i8 0, align 1, !dbg !48
@__init_end = global i8 0, align 1, !dbg !50
@_device_list_start = global i8 0, align 1, !dbg !52
@_device_list_end = global i8 0, align 1, !dbg !54
@__device_area_start = global i8 0, align 1, !dbg !56
@__device_area_load_start = global i8 0, align 1, !dbg !58
@__device_area_end = global i8 0, align 1, !dbg !60
@__sw_isr_table_start = global i8 0, align 1, !dbg !62
@__sw_isr_table_load_start = global i8 0, align 1, !dbg !64
@__sw_isr_table_end = global i8 0, align 1, !dbg !66
@__sw_isr_table_size = global i8 0, align 1, !dbg !68
@__initlevel_error_start = global i8 0, align 1, !dbg !70
@__initlevel_error_load_start = global i8 0, align 1, !dbg !72
@__initlevel_error_end = global i8 0, align 1, !dbg !74
@__app_shmem_regions_start = global i8 0, align 1, !dbg !76
@__app_shmem_regions_load_start = global i8 0, align 1, !dbg !78
@__app_shmem_regions_end = global i8 0, align 1, !dbg !80
@_bt_l2cap_fixed_chan_list_start = global i8 0, align 1, !dbg !82
@_bt_l2cap_fixed_chan_list_end = global i8 0, align 1, !dbg !84
@__bt_l2cap_fixed_chan_area_start = global i8 0, align 1, !dbg !86
@__bt_l2cap_fixed_chan_area_load_start = global i8 0, align 1, !dbg !88
@__bt_l2cap_fixed_chan_area_end = global i8 0, align 1, !dbg !90
@_bt_gatt_service_static_list_start = global i8 0, align 1, !dbg !92
@_bt_gatt_service_static_list_end = global i8 0, align 1, !dbg !94
@__bt_gatt_service_static_area_start = global i8 0, align 1, !dbg !96
@__bt_gatt_service_static_area_load_start = global i8 0, align 1, !dbg !98
@__bt_gatt_service_static_area_end = global i8 0, align 1, !dbg !100
@_k_p4wq_initparam_list_start = global i8 0, align 1, !dbg !102
@_k_p4wq_initparam_list_end = global i8 0, align 1, !dbg !104
@__k_p4wq_initparam_area_start = global i8 0, align 1, !dbg !106
@__k_p4wq_initparam_area_load_start = global i8 0, align 1, !dbg !108
@__k_p4wq_initparam_area_end = global i8 0, align 1, !dbg !110
@_log_strings_list_start = global i8 0, align 1, !dbg !112
@_log_strings_list_end = global i8 0, align 1, !dbg !114
@__log_strings_area_start = global i8 0, align 1, !dbg !116
@__log_strings_area_load_start = global i8 0, align 1, !dbg !118
@__log_strings_area_end = global i8 0, align 1, !dbg !120
@_log_const_list_start = global i8 0, align 1, !dbg !122
@_log_const_list_end = global i8 0, align 1, !dbg !124
@__log_const_area_start = global i8 0, align 1, !dbg !126
@__log_const_area_load_start = global i8 0, align 1, !dbg !128
@__log_const_area_end = global i8 0, align 1, !dbg !130
@_shell_list_start = global i8 0, align 1, !dbg !132
@_shell_list_end = global i8 0, align 1, !dbg !134
@__shell_area_start = global i8 0, align 1, !dbg !136
@__shell_area_load_start = global i8 0, align 1, !dbg !138
@__shell_area_end = global i8 0, align 1, !dbg !140
@_shell_root_cmds_list_start = global i8 0, align 1, !dbg !142
@_shell_root_cmds_list_end = global i8 0, align 1, !dbg !144
@__shell_root_cmds_area_start = global i8 0, align 1, !dbg !146
@__shell_root_cmds_area_load_start = global i8 0, align 1, !dbg !148
@__shell_root_cmds_area_end = global i8 0, align 1, !dbg !150
@_shell_subcmds_list_start = global i8 0, align 1, !dbg !152
@_shell_subcmds_list_end = global i8 0, align 1, !dbg !154
@__shell_subcmds_area_start = global i8 0, align 1, !dbg !156
@__shell_subcmds_area_load_start = global i8 0, align 1, !dbg !158
@__shell_subcmds_area_end = global i8 0, align 1, !dbg !160
@_shell_dynamic_subcmds_list_start = global i8 0, align 1, !dbg !162
@_shell_dynamic_subcmds_list_end = global i8 0, align 1, !dbg !164
@__shell_dynamic_subcmds_area_start = global i8 0, align 1, !dbg !166
@__shell_dynamic_subcmds_area_load_start = global i8 0, align 1, !dbg !168
@__shell_dynamic_subcmds_area_end = global i8 0, align 1, !dbg !170
@_cfb_font_list_start = global i8 0, align 1, !dbg !172
@_cfb_font_list_end = global i8 0, align 1, !dbg !174
@__cfb_font_area_start = global i8 0, align 1, !dbg !176
@__cfb_font_area_load_start = global i8 0, align 1, !dbg !178
@__cfb_font_area_end = global i8 0, align 1, !dbg !180
@_tracing_backend_list_start = global i8 0, align 1, !dbg !182
@_tracing_backend_list_end = global i8 0, align 1, !dbg !184
@__tracing_backend_area_start = global i8 0, align 1, !dbg !186
@__tracing_backend_area_load_start = global i8 0, align 1, !dbg !188
@__tracing_backend_area_end = global i8 0, align 1, !dbg !190
@__zephyr_dbg_info_start = global i8 0, align 1, !dbg !192
@__zephyr_dbg_info_load_start = global i8 0, align 1, !dbg !194
@__zephyr_dbg_info_end = global i8 0, align 1, !dbg !196
@__zephyr_dbg_info_size = global i8 0, align 1, !dbg !198
@__static_thread_data_list_start = global i8 0, align 1, !dbg !200
@__static_thread_data_list_end = global i8 0, align 1, !dbg !202
@___static_thread_data_area_start = global i8 0, align 1, !dbg !204
@___static_thread_data_area_load_start = global i8 0, align 1, !dbg !206
@___static_thread_data_area_end = global i8 0, align 1, !dbg !208
@_log_link_list_start = global i8 0, align 1, !dbg !210
@_log_link_list_end = global i8 0, align 1, !dbg !212
@__log_link_area_start = global i8 0, align 1, !dbg !214
@__log_link_area_load_start = global i8 0, align 1, !dbg !216
@__log_link_area_end = global i8 0, align 1, !dbg !218
@_log_backend_list_start = global i8 0, align 1, !dbg !220
@_log_backend_list_end = global i8 0, align 1, !dbg !222
@__log_backend_area_start = global i8 0, align 1, !dbg !224
@__log_backend_area_load_start = global i8 0, align 1, !dbg !226
@__log_backend_area_end = global i8 0, align 1, !dbg !228
@__rodata_start = global i8 0, align 1, !dbg !230
@__rodata_load_start = global i8 0, align 1, !dbg !232
@__rodata_end = global i8 0, align 1, !dbg !234
@__rodata_size = global i8 0, align 1, !dbg !236
@__ARM_exidx_start = global i8 0, align 1, !dbg !238
@__ARM_exidx_load_start = global i8 0, align 1, !dbg !240
@__ARM_exidx_end = global i8 0, align 1, !dbg !242
@__ARM_exidx_size = global i8 0, align 1, !dbg !244
@__data_load_start = global i8 0, align 1, !dbg !246
@__data_end = global i8 0, align 1, !dbg !248
@__data_size = global i8 0, align 1, !dbg !250
@__device_states_start = global i8 0, align 1, !dbg !252
@__device_states_load_start = global i8 0, align 1, !dbg !254
@__device_states_end = global i8 0, align 1, !dbg !256
@__device_states_size = global i8 0, align 1, !dbg !258
@_log_dynamic_list_start = global i8 0, align 1, !dbg !260
@_log_dynamic_list_end = global i8 0, align 1, !dbg !262
@__log_dynamic_area_start = global i8 0, align 1, !dbg !264
@__log_dynamic_area_load_start = global i8 0, align 1, !dbg !266
@__log_dynamic_area_end = global i8 0, align 1, !dbg !268
@_k_timer_list_start = global i8 0, align 1, !dbg !270
@_k_timer_list_end = global i8 0, align 1, !dbg !272
@__k_timer_area_start = global i8 0, align 1, !dbg !274
@__k_timer_area_load_start = global i8 0, align 1, !dbg !276
@__k_timer_area_end = global i8 0, align 1, !dbg !278
@_k_mem_slab_list_start = global i8 0, align 1, !dbg !280
@_k_mem_slab_list_end = global i8 0, align 1, !dbg !282
@__k_mem_slab_area_start = global i8 0, align 1, !dbg !284
@__k_mem_slab_area_load_start = global i8 0, align 1, !dbg !286
@__k_mem_slab_area_end = global i8 0, align 1, !dbg !288
@_k_heap_list_start = global i8 0, align 1, !dbg !290
@_k_heap_list_end = global i8 0, align 1, !dbg !292
@__k_heap_area_start = global i8 0, align 1, !dbg !294
@__k_heap_area_load_start = global i8 0, align 1, !dbg !296
@__k_heap_area_end = global i8 0, align 1, !dbg !298
@_k_mutex_list_start = global i8 0, align 1, !dbg !300
@_k_mutex_list_end = global i8 0, align 1, !dbg !302
@__k_mutex_area_start = global i8 0, align 1, !dbg !304
@__k_mutex_area_load_start = global i8 0, align 1, !dbg !306
@__k_mutex_area_end = global i8 0, align 1, !dbg !308
@_k_stack_list_start = global i8 0, align 1, !dbg !310
@_k_stack_list_end = global i8 0, align 1, !dbg !312
@__k_stack_area_start = global i8 0, align 1, !dbg !314
@__k_stack_area_load_start = global i8 0, align 1, !dbg !316
@__k_stack_area_end = global i8 0, align 1, !dbg !318
@_k_msgq_list_start = global i8 0, align 1, !dbg !320
@_k_msgq_list_end = global i8 0, align 1, !dbg !322
@__k_msgq_area_start = global i8 0, align 1, !dbg !324
@__k_msgq_area_load_start = global i8 0, align 1, !dbg !326
@__k_msgq_area_end = global i8 0, align 1, !dbg !328
@_k_mbox_list_start = global i8 0, align 1, !dbg !330
@_k_mbox_list_end = global i8 0, align 1, !dbg !332
@__k_mbox_area_start = global i8 0, align 1, !dbg !334
@__k_mbox_area_load_start = global i8 0, align 1, !dbg !336
@__k_mbox_area_end = global i8 0, align 1, !dbg !338
@_k_pipe_list_start = global i8 0, align 1, !dbg !340
@_k_pipe_list_end = global i8 0, align 1, !dbg !342
@__k_pipe_area_start = global i8 0, align 1, !dbg !344
@__k_pipe_area_load_start = global i8 0, align 1, !dbg !346
@__k_pipe_area_end = global i8 0, align 1, !dbg !348
@_k_sem_list_start = global i8 0, align 1, !dbg !350
@_k_sem_list_end = global i8 0, align 1, !dbg !352
@__k_sem_area_start = global i8 0, align 1, !dbg !354
@__k_sem_area_load_start = global i8 0, align 1, !dbg !356
@__k_sem_area_end = global i8 0, align 1, !dbg !358
@_k_queue_list_start = global i8 0, align 1, !dbg !360
@_k_queue_list_end = global i8 0, align 1, !dbg !362
@__k_queue_area_start = global i8 0, align 1, !dbg !364
@__k_queue_area_load_start = global i8 0, align 1, !dbg !366
@__k_queue_area_end = global i8 0, align 1, !dbg !368
@_k_condvar_list_start = global i8 0, align 1, !dbg !370
@_k_condvar_list_end = global i8 0, align 1, !dbg !372
@__k_condvar_area_start = global i8 0, align 1, !dbg !374
@__k_condvar_area_load_start = global i8 0, align 1, !dbg !376
@__k_condvar_area_end = global i8 0, align 1, !dbg !378
@_k_event_list_start = global i8 0, align 1, !dbg !380
@_k_event_list_end = global i8 0, align 1, !dbg !382
@__k_event_area_start = global i8 0, align 1, !dbg !384
@__k_event_area_load_start = global i8 0, align 1, !dbg !386
@__k_event_area_end = global i8 0, align 1, !dbg !388
@_net_buf_pool_list_start = global i8 0, align 1, !dbg !390
@_net_buf_pool_list_end = global i8 0, align 1, !dbg !392
@__net_buf_pool_area_start = global i8 0, align 1, !dbg !394
@__net_buf_pool_area_load_start = global i8 0, align 1, !dbg !396
@__net_buf_pool_area_end = global i8 0, align 1, !dbg !398
@_log_mpsc_pbuf_list_start = global i8 0, align 1, !dbg !400
@_log_mpsc_pbuf_list_end = global i8 0, align 1, !dbg !402
@__log_mpsc_pbuf_area_start = global i8 0, align 1, !dbg !404
@__log_mpsc_pbuf_area_load_start = global i8 0, align 1, !dbg !406
@__log_mpsc_pbuf_area_end = global i8 0, align 1, !dbg !408
@_log_msg_ptr_list_start = global i8 0, align 1, !dbg !410
@_log_msg_ptr_list_end = global i8 0, align 1, !dbg !412
@__log_msg_ptr_area_start = global i8 0, align 1, !dbg !414
@__log_msg_ptr_area_load_start = global i8 0, align 1, !dbg !416
@__log_msg_ptr_area_end = global i8 0, align 1, !dbg !418
@__ramfunc_start = global i8 0, align 1, !dbg !420
@__ramfunc_load_start = global i8 0, align 1, !dbg !422
@__ramfunc_end = global i8 0, align 1, !dbg !424
@__ramfunc_size = global i8 0, align 1, !dbg !426
@__noinit_start = global i8 0, align 1, !dbg !428
@__noinit_load_start = global i8 0, align 1, !dbg !430
@__noinit_end = global i8 0, align 1, !dbg !432
@__noinit_size = global i8 0, align 1, !dbg !434
@__bss_start = global i8 0, align 1, !dbg !436
@__bss_load_start = global i8 0, align 1, !dbg !438
@__bss_end = global i8 0, align 1, !dbg !440
@__bss_size = global i8 0, align 1, !dbg !442
@__last_ram_section_start = global i8 0, align 1, !dbg !444
@__last_ram_section_load_start = global i8 0, align 1, !dbg !446
@__last_ram_section_end = global i8 0, align 1, !dbg !448
@__last_ram_section_size = global i8 0, align 1, !dbg !450
@__rom_region_start = global i8 0, align 1, !dbg !452
@__rom_region_load_start = global i8 0, align 1, !dbg !454
@__rom_region_end = global i8 0, align 1, !dbg !456
@__text_region_start = global i8 0, align 1, !dbg !458
@__text_region_load_start = global i8 0, align 1, !dbg !460
@__text_region_end = global i8 0, align 1, !dbg !462
@__rodata_region_start = global i8 0, align 1, !dbg !464
@__rodata_region_load_start = global i8 0, align 1, !dbg !466
@__rodata_region_end = global i8 0, align 1, !dbg !468
@__ram_region_start = global i8 0, align 1, !dbg !470
@__ram_region_load_start = global i8 0, align 1, !dbg !472
@__ram_region_end = global i8 0, align 1, !dbg !474
@__data_region_start = global i8 0, align 1, !dbg !476
@__data_region_load_start = global i8 0, align 1, !dbg !478
@__data_region_end = global i8 0, align 1, !dbg !480
@__kernel_ram_start = global i8 0, align 1, !dbg !482
@__kernel_ram_end = global i8 0, align 1, !dbg !484
@__kernel_ram_size = global i8 0, align 1, !dbg !486
@_image_ram_start = global i8 0, align 1, !dbg !488
@ARM_LIB_STACKHEAP = global i8 0, align 1, !dbg !490
@__init_size = global i8 0, align 1, !dbg !492
@__device_area_size = global i8 0, align 1, !dbg !494
@__initlevel_error_size = global i8 0, align 1, !dbg !496
@__app_shmem_regions_size = global i8 0, align 1, !dbg !498
@__bt_l2cap_fixed_chan_area_size = global i8 0, align 1, !dbg !500
@__bt_gatt_service_static_area_size = global i8 0, align 1, !dbg !502
@__k_p4wq_initparam_area_size = global i8 0, align 1, !dbg !504
@__log_strings_area_size = global i8 0, align 1, !dbg !506
@__log_const_area_size = global i8 0, align 1, !dbg !508
@__shell_area_size = global i8 0, align 1, !dbg !510
@__shell_root_cmds_area_size = global i8 0, align 1, !dbg !512
@__shell_subcmds_area_size = global i8 0, align 1, !dbg !514
@__shell_dynamic_subcmds_area_size = global i8 0, align 1, !dbg !516
@__cfb_font_area_size = global i8 0, align 1, !dbg !518
@__tracing_backend_area_size = global i8 0, align 1, !dbg !520
@___static_thread_data_area_size = global i8 0, align 1, !dbg !522
@__log_link_area_size = global i8 0, align 1, !dbg !524
@__log_backend_area_size = global i8 0, align 1, !dbg !526
@__log_dynamic_area_size = global i8 0, align 1, !dbg !528
@__k_timer_area_size = global i8 0, align 1, !dbg !530
@__k_mem_slab_area_size = global i8 0, align 1, !dbg !532
@__k_heap_area_size = global i8 0, align 1, !dbg !534
@__k_mutex_area_size = global i8 0, align 1, !dbg !536
@__k_stack_area_size = global i8 0, align 1, !dbg !538
@__k_msgq_area_size = global i8 0, align 1, !dbg !540
@__k_mbox_area_size = global i8 0, align 1, !dbg !542
@__k_pipe_area_size = global i8 0, align 1, !dbg !544
@__k_sem_area_size = global i8 0, align 1, !dbg !546
@__k_queue_area_size = global i8 0, align 1, !dbg !548
@__k_condvar_area_size = global i8 0, align 1, !dbg !550
@__k_event_area_size = global i8 0, align 1, !dbg !552
@__net_buf_pool_area_size = global i8 0, align 1, !dbg !554
@__log_mpsc_pbuf_area_size = global i8 0, align 1, !dbg !556
@__log_msg_ptr_area_size = global i8 0, align 1, !dbg !558
@__rom_region_size = global i8 0, align 1, !dbg !560
@__text_region_size = global i8 0, align 1, !dbg !562
@__rodata_region_size = global i8 0, align 1, !dbg !564
@__ram_region_size = global i8 0, align 1, !dbg !566
@__data_region_size = global i8 0, align 1, !dbg !568
@_ram_vector_start = global i8 0, align 1, !dbg !570
@__aeabi_ctype_table_ = constant [257 x i8] zeroinitializer, align 1, !dbg !572

; Function Attrs: noinline nounwind optnone uwtable
define i32 @readFromIntrinsicRetInt() #0 !dbg !587 {
  ret i32 0, !dbg !590
}

; Function Attrs: noinline nounwind optnone uwtable
define void @z_arm_int_exit() #0 !dbg !591 {
  ret void, !dbg !594
}

; Function Attrs: noinline nounwind optnone uwtable
define void @z_arm_fatal_error(i32 noundef %0, ptr noundef %1) #0 !dbg !595 {
  %3 = alloca i32, align 4
  %4 = alloca ptr, align 4
  store i32 %0, ptr %3, align 4
  call void @llvm.dbg.declare(metadata ptr %3, metadata !602, metadata !DIExpression()), !dbg !603
  store ptr %1, ptr %4, align 4
  call void @llvm.dbg.declare(metadata ptr %4, metadata !604, metadata !DIExpression()), !dbg !605
  ret void, !dbg !606
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.declare(metadata, metadata, metadata) #1

; Function Attrs: noinline nounwind optnone uwtable
define void @arch_cpu_atomic_idle(i32 noundef %0) #0 !dbg !607 {
  %2 = alloca i32, align 4
  store i32 %0, ptr %2, align 4
  call void @llvm.dbg.declare(metadata ptr %2, metadata !610, metadata !DIExpression()), !dbg !611
  ret void, !dbg !612
}

; Function Attrs: noinline nounwind optnone uwtable
define void @z_check_thread_stack_fail(i32 noundef %0) #0 !dbg !613 {
  %2 = alloca i32, align 4
  store i32 %0, ptr %2, align 4
  call void @llvm.dbg.declare(metadata ptr %2, metadata !618, metadata !DIExpression()), !dbg !619
  ret void, !dbg !620
}

; Function Attrs: noinline nounwind optnone uwtable
define void @arch_cpu_idle() #0 !dbg !621 {
  ret void, !dbg !622
}

; Function Attrs: noinline nounwind optnone uwtable
define void @z_arm_cpu_idle_init() #0 !dbg !623 {
  ret void, !dbg !624
}

; Function Attrs: noinline nounwind optnone uwtable
define void @arch_switch_to_main_thread(ptr noundef %0, ptr noundef %1, i32 noundef %2, i32 noundef %3) #0 !dbg !625 {
  %5 = alloca ptr, align 4
  %6 = alloca ptr, align 4
  %7 = alloca i32, align 4
  %8 = alloca i32, align 4
  store ptr %0, ptr %5, align 4
  call void @llvm.dbg.declare(metadata ptr %5, metadata !631, metadata !DIExpression()), !dbg !632
  store ptr %1, ptr %6, align 4
  call void @llvm.dbg.declare(metadata ptr %6, metadata !633, metadata !DIExpression()), !dbg !634
  store i32 %2, ptr %7, align 4
  call void @llvm.dbg.declare(metadata ptr %7, metadata !635, metadata !DIExpression()), !dbg !636
  store i32 %3, ptr %8, align 4
  call void @llvm.dbg.declare(metadata ptr %8, metadata !637, metadata !DIExpression()), !dbg !638
  ret void, !dbg !639
}

; Function Attrs: noinline nounwind optnone uwtable
define void @z_SysNmiOnReset(i32 noundef %0) #0 !dbg !640 {
  %2 = alloca i32, align 4
  store i32 %0, ptr %2, align 4
  call void @llvm.dbg.declare(metadata ptr %2, metadata !641, metadata !DIExpression()), !dbg !642
  ret void, !dbg !643
}

; Function Attrs: noinline nounwind optnone uwtable
define void @arch_new_thread(ptr noundef %0, ptr noundef %1, i32 noundef %2, i32 noundef %3, ptr noundef %4, ptr noundef %5, ptr noundef %6, i32 noundef %7, i32 noundef %8) #0 !dbg !644 {
  %10 = alloca ptr, align 4
  %11 = alloca ptr, align 4
  %12 = alloca i32, align 4
  %13 = alloca i32, align 4
  %14 = alloca ptr, align 4
  %15 = alloca ptr, align 4
  %16 = alloca ptr, align 4
  %17 = alloca i32, align 4
  %18 = alloca i32, align 4
  store ptr %0, ptr %10, align 4
  call void @llvm.dbg.declare(metadata ptr %10, metadata !647, metadata !DIExpression()), !dbg !648
  store ptr %1, ptr %11, align 4
  call void @llvm.dbg.declare(metadata ptr %11, metadata !649, metadata !DIExpression()), !dbg !650
  store i32 %2, ptr %12, align 4
  call void @llvm.dbg.declare(metadata ptr %12, metadata !651, metadata !DIExpression()), !dbg !652
  store i32 %3, ptr %13, align 4
  call void @llvm.dbg.declare(metadata ptr %13, metadata !653, metadata !DIExpression()), !dbg !654
  store ptr %4, ptr %14, align 4
  call void @llvm.dbg.declare(metadata ptr %14, metadata !655, metadata !DIExpression()), !dbg !656
  store ptr %5, ptr %15, align 4
  call void @llvm.dbg.declare(metadata ptr %15, metadata !657, metadata !DIExpression()), !dbg !658
  store ptr %6, ptr %16, align 4
  call void @llvm.dbg.declare(metadata ptr %16, metadata !659, metadata !DIExpression()), !dbg !660
  store i32 %7, ptr %17, align 4
  call void @llvm.dbg.declare(metadata ptr %17, metadata !661, metadata !DIExpression()), !dbg !662
  store i32 %8, ptr %18, align 4
  call void @llvm.dbg.declare(metadata ptr %18, metadata !663, metadata !DIExpression()), !dbg !664
  ret void, !dbg !665
}

attributes #0 = { noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="i686" "target-features"="+cmov,+cx8,+x87" "tune-cpu"="generic" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.dbg.cu = !{!2}
!llvm.module.flags = !{!579, !580, !581, !582, !583, !584, !585}
!llvm.ident = !{!586}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "__aeabi_EDOM", scope: !2, file: !3, line: 359, type: !7, isLocal: false, isDefinition: true)
!2 = distinct !DICompileUnit(language: DW_LANG_C11, file: !3, producer: "Ubuntu clang version 17.0.4 (++20231031083134+309d55140c46-1~exp1~20231031083240.62)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, globals: !4, splitDebugInlining: false, nameTableKind: None)
!3 = !DIFile(filename: "externalLinking.c", directory: "/home/sri/Rehosting-armclang/src", checksumkind: CSK_MD5, checksum: "7bb6a23053c0edc7921b518636aa6905")
!4 = !{!0, !5, !9, !11, !14, !16, !18, !20, !22, !24, !26, !28, !30, !32, !34, !36, !38, !40, !42, !44, !46, !48, !50, !52, !54, !56, !58, !60, !62, !64, !66, !68, !70, !72, !74, !76, !78, !80, !82, !84, !86, !88, !90, !92, !94, !96, !98, !100, !102, !104, !106, !108, !110, !112, !114, !116, !118, !120, !122, !124, !126, !128, !130, !132, !134, !136, !138, !140, !142, !144, !146, !148, !150, !152, !154, !156, !158, !160, !162, !164, !166, !168, !170, !172, !174, !176, !178, !180, !182, !184, !186, !188, !190, !192, !194, !196, !198, !200, !202, !204, !206, !208, !210, !212, !214, !216, !218, !220, !222, !224, !226, !228, !230, !232, !234, !236, !238, !240, !242, !244, !246, !248, !250, !252, !254, !256, !258, !260, !262, !264, !266, !268, !270, !272, !274, !276, !278, !280, !282, !284, !286, !288, !290, !292, !294, !296, !298, !300, !302, !304, !306, !308, !310, !312, !314, !316, !318, !320, !322, !324, !326, !328, !330, !332, !334, !336, !338, !340, !342, !344, !346, !348, !350, !352, !354, !356, !358, !360, !362, !364, !366, !368, !370, !372, !374, !376, !378, !380, !382, !384, !386, !388, !390, !392, !394, !396, !398, !400, !402, !404, !406, !408, !410, !412, !414, !416, !418, !420, !422, !424, !426, !428, !430, !432, !434, !436, !438, !440, !442, !444, !446, !448, !450, !452, !454, !456, !458, !460, !462, !464, !466, !468, !470, !472, !474, !476, !478, !480, !482, !484, !486, !488, !490, !492, !494, !496, !498, !500, !502, !504, !506, !508, !510, !512, !514, !516, !518, !520, !522, !524, !526, !528, !530, !532, !534, !536, !538, !540, !542, !544, !546, !548, !550, !552, !554, !556, !558, !560, !562, !564, !566, !568, !570, !572}
!5 = !DIGlobalVariableExpression(var: !6, expr: !DIExpression())
!6 = distinct !DIGlobalVariable(name: "__aeabi_ERANGE", scope: !2, file: !3, line: 360, type: !7, isLocal: false, isDefinition: true)
!7 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !8)
!8 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!9 = !DIGlobalVariableExpression(var: !10, expr: !DIExpression())
!10 = distinct !DIGlobalVariable(name: "__aeabi_EILSEQ", scope: !2, file: !3, line: 361, type: !7, isLocal: false, isDefinition: true)
!11 = !DIGlobalVariableExpression(var: !12, expr: !DIExpression())
!12 = distinct !DIGlobalVariable(name: "_vector_start", scope: !2, file: !3, line: 20, type: !13, isLocal: false, isDefinition: true)
!13 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!14 = !DIGlobalVariableExpression(var: !15, expr: !DIExpression())
!15 = distinct !DIGlobalVariable(name: "_vector_end", scope: !2, file: !3, line: 21, type: !13, isLocal: false, isDefinition: true)
!16 = !DIGlobalVariableExpression(var: !17, expr: !DIExpression())
!17 = distinct !DIGlobalVariable(name: "__rom_start_start", scope: !2, file: !3, line: 22, type: !13, isLocal: false, isDefinition: true)
!18 = !DIGlobalVariableExpression(var: !19, expr: !DIExpression())
!19 = distinct !DIGlobalVariable(name: "__rom_start_load_start", scope: !2, file: !3, line: 23, type: !13, isLocal: false, isDefinition: true)
!20 = !DIGlobalVariableExpression(var: !21, expr: !DIExpression())
!21 = distinct !DIGlobalVariable(name: "__rom_start_end", scope: !2, file: !3, line: 25, type: !13, isLocal: false, isDefinition: true)
!22 = !DIGlobalVariableExpression(var: !23, expr: !DIExpression())
!23 = distinct !DIGlobalVariable(name: "__rom_start_size", scope: !2, file: !3, line: 26, type: !13, isLocal: false, isDefinition: true)
!24 = !DIGlobalVariableExpression(var: !25, expr: !DIExpression())
!25 = distinct !DIGlobalVariable(name: "__text_start", scope: !2, file: !3, line: 27, type: !13, isLocal: false, isDefinition: true)
!26 = !DIGlobalVariableExpression(var: !27, expr: !DIExpression())
!27 = distinct !DIGlobalVariable(name: "__text_load_start", scope: !2, file: !3, line: 28, type: !13, isLocal: false, isDefinition: true)
!28 = !DIGlobalVariableExpression(var: !29, expr: !DIExpression())
!29 = distinct !DIGlobalVariable(name: "__text_end", scope: !2, file: !3, line: 29, type: !13, isLocal: false, isDefinition: true)
!30 = !DIGlobalVariableExpression(var: !31, expr: !DIExpression())
!31 = distinct !DIGlobalVariable(name: "__text_size", scope: !2, file: !3, line: 30, type: !13, isLocal: false, isDefinition: true)
!32 = !DIGlobalVariableExpression(var: !33, expr: !DIExpression())
!33 = distinct !DIGlobalVariable(name: "__init_EARLY_start", scope: !2, file: !3, line: 31, type: !13, isLocal: false, isDefinition: true)
!34 = !DIGlobalVariableExpression(var: !35, expr: !DIExpression())
!35 = distinct !DIGlobalVariable(name: "__init_PRE_KERNEL_1_start", scope: !2, file: !3, line: 32, type: !13, isLocal: false, isDefinition: true)
!36 = !DIGlobalVariableExpression(var: !37, expr: !DIExpression())
!37 = distinct !DIGlobalVariable(name: "__init_PRE_KERNEL_2_start", scope: !2, file: !3, line: 33, type: !13, isLocal: false, isDefinition: true)
!38 = !DIGlobalVariableExpression(var: !39, expr: !DIExpression())
!39 = distinct !DIGlobalVariable(name: "__init_POST_KERNEL_start", scope: !2, file: !3, line: 34, type: !13, isLocal: false, isDefinition: true)
!40 = !DIGlobalVariableExpression(var: !41, expr: !DIExpression())
!41 = distinct !DIGlobalVariable(name: "__init_APPLICATION_start", scope: !2, file: !3, line: 35, type: !13, isLocal: false, isDefinition: true)
!42 = !DIGlobalVariableExpression(var: !43, expr: !DIExpression())
!43 = distinct !DIGlobalVariable(name: "__init_SMP_start", scope: !2, file: !3, line: 36, type: !13, isLocal: false, isDefinition: true)
!44 = !DIGlobalVariableExpression(var: !45, expr: !DIExpression())
!45 = distinct !DIGlobalVariable(name: "__init_start", scope: !2, file: !3, line: 37, type: !13, isLocal: false, isDefinition: true)
!46 = !DIGlobalVariableExpression(var: !47, expr: !DIExpression())
!47 = distinct !DIGlobalVariable(name: "__init_load_start", scope: !2, file: !3, line: 38, type: !13, isLocal: false, isDefinition: true)
!48 = !DIGlobalVariableExpression(var: !49, expr: !DIExpression())
!49 = distinct !DIGlobalVariable(name: "_isr_wrapper", scope: !2, file: !3, line: 40, type: !13, isLocal: false, isDefinition: true)
!50 = !DIGlobalVariableExpression(var: !51, expr: !DIExpression())
!51 = distinct !DIGlobalVariable(name: "__init_end", scope: !2, file: !3, line: 41, type: !13, isLocal: false, isDefinition: true)
!52 = !DIGlobalVariableExpression(var: !53, expr: !DIExpression())
!53 = distinct !DIGlobalVariable(name: "_device_list_start", scope: !2, file: !3, line: 42, type: !13, isLocal: false, isDefinition: true)
!54 = !DIGlobalVariableExpression(var: !55, expr: !DIExpression())
!55 = distinct !DIGlobalVariable(name: "_device_list_end", scope: !2, file: !3, line: 43, type: !13, isLocal: false, isDefinition: true)
!56 = !DIGlobalVariableExpression(var: !57, expr: !DIExpression())
!57 = distinct !DIGlobalVariable(name: "__device_area_start", scope: !2, file: !3, line: 44, type: !13, isLocal: false, isDefinition: true)
!58 = !DIGlobalVariableExpression(var: !59, expr: !DIExpression())
!59 = distinct !DIGlobalVariable(name: "__device_area_load_start", scope: !2, file: !3, line: 45, type: !13, isLocal: false, isDefinition: true)
!60 = !DIGlobalVariableExpression(var: !61, expr: !DIExpression())
!61 = distinct !DIGlobalVariable(name: "__device_area_end", scope: !2, file: !3, line: 47, type: !13, isLocal: false, isDefinition: true)
!62 = !DIGlobalVariableExpression(var: !63, expr: !DIExpression())
!63 = distinct !DIGlobalVariable(name: "__sw_isr_table_start", scope: !2, file: !3, line: 48, type: !13, isLocal: false, isDefinition: true)
!64 = !DIGlobalVariableExpression(var: !65, expr: !DIExpression())
!65 = distinct !DIGlobalVariable(name: "__sw_isr_table_load_start", scope: !2, file: !3, line: 49, type: !13, isLocal: false, isDefinition: true)
!66 = !DIGlobalVariableExpression(var: !67, expr: !DIExpression())
!67 = distinct !DIGlobalVariable(name: "__sw_isr_table_end", scope: !2, file: !3, line: 51, type: !13, isLocal: false, isDefinition: true)
!68 = !DIGlobalVariableExpression(var: !69, expr: !DIExpression())
!69 = distinct !DIGlobalVariable(name: "__sw_isr_table_size", scope: !2, file: !3, line: 52, type: !13, isLocal: false, isDefinition: true)
!70 = !DIGlobalVariableExpression(var: !71, expr: !DIExpression())
!71 = distinct !DIGlobalVariable(name: "__initlevel_error_start", scope: !2, file: !3, line: 53, type: !13, isLocal: false, isDefinition: true)
!72 = !DIGlobalVariableExpression(var: !73, expr: !DIExpression())
!73 = distinct !DIGlobalVariable(name: "__initlevel_error_load_start", scope: !2, file: !3, line: 54, type: !13, isLocal: false, isDefinition: true)
!74 = !DIGlobalVariableExpression(var: !75, expr: !DIExpression())
!75 = distinct !DIGlobalVariable(name: "__initlevel_error_end", scope: !2, file: !3, line: 56, type: !13, isLocal: false, isDefinition: true)
!76 = !DIGlobalVariableExpression(var: !77, expr: !DIExpression())
!77 = distinct !DIGlobalVariable(name: "__app_shmem_regions_start", scope: !2, file: !3, line: 57, type: !13, isLocal: false, isDefinition: true)
!78 = !DIGlobalVariableExpression(var: !79, expr: !DIExpression())
!79 = distinct !DIGlobalVariable(name: "__app_shmem_regions_load_start", scope: !2, file: !3, line: 58, type: !13, isLocal: false, isDefinition: true)
!80 = !DIGlobalVariableExpression(var: !81, expr: !DIExpression())
!81 = distinct !DIGlobalVariable(name: "__app_shmem_regions_end", scope: !2, file: !3, line: 60, type: !13, isLocal: false, isDefinition: true)
!82 = !DIGlobalVariableExpression(var: !83, expr: !DIExpression())
!83 = distinct !DIGlobalVariable(name: "_bt_l2cap_fixed_chan_list_start", scope: !2, file: !3, line: 61, type: !13, isLocal: false, isDefinition: true)
!84 = !DIGlobalVariableExpression(var: !85, expr: !DIExpression())
!85 = distinct !DIGlobalVariable(name: "_bt_l2cap_fixed_chan_list_end", scope: !2, file: !3, line: 62, type: !13, isLocal: false, isDefinition: true)
!86 = !DIGlobalVariableExpression(var: !87, expr: !DIExpression())
!87 = distinct !DIGlobalVariable(name: "__bt_l2cap_fixed_chan_area_start", scope: !2, file: !3, line: 63, type: !13, isLocal: false, isDefinition: true)
!88 = !DIGlobalVariableExpression(var: !89, expr: !DIExpression())
!89 = distinct !DIGlobalVariable(name: "__bt_l2cap_fixed_chan_area_load_start", scope: !2, file: !3, line: 64, type: !13, isLocal: false, isDefinition: true)
!90 = !DIGlobalVariableExpression(var: !91, expr: !DIExpression())
!91 = distinct !DIGlobalVariable(name: "__bt_l2cap_fixed_chan_area_end", scope: !2, file: !3, line: 66, type: !13, isLocal: false, isDefinition: true)
!92 = !DIGlobalVariableExpression(var: !93, expr: !DIExpression())
!93 = distinct !DIGlobalVariable(name: "_bt_gatt_service_static_list_start", scope: !2, file: !3, line: 67, type: !13, isLocal: false, isDefinition: true)
!94 = !DIGlobalVariableExpression(var: !95, expr: !DIExpression())
!95 = distinct !DIGlobalVariable(name: "_bt_gatt_service_static_list_end", scope: !2, file: !3, line: 68, type: !13, isLocal: false, isDefinition: true)
!96 = !DIGlobalVariableExpression(var: !97, expr: !DIExpression())
!97 = distinct !DIGlobalVariable(name: "__bt_gatt_service_static_area_start", scope: !2, file: !3, line: 69, type: !13, isLocal: false, isDefinition: true)
!98 = !DIGlobalVariableExpression(var: !99, expr: !DIExpression())
!99 = distinct !DIGlobalVariable(name: "__bt_gatt_service_static_area_load_start", scope: !2, file: !3, line: 70, type: !13, isLocal: false, isDefinition: true)
!100 = !DIGlobalVariableExpression(var: !101, expr: !DIExpression())
!101 = distinct !DIGlobalVariable(name: "__bt_gatt_service_static_area_end", scope: !2, file: !3, line: 72, type: !13, isLocal: false, isDefinition: true)
!102 = !DIGlobalVariableExpression(var: !103, expr: !DIExpression())
!103 = distinct !DIGlobalVariable(name: "_k_p4wq_initparam_list_start", scope: !2, file: !3, line: 73, type: !13, isLocal: false, isDefinition: true)
!104 = !DIGlobalVariableExpression(var: !105, expr: !DIExpression())
!105 = distinct !DIGlobalVariable(name: "_k_p4wq_initparam_list_end", scope: !2, file: !3, line: 74, type: !13, isLocal: false, isDefinition: true)
!106 = !DIGlobalVariableExpression(var: !107, expr: !DIExpression())
!107 = distinct !DIGlobalVariable(name: "__k_p4wq_initparam_area_start", scope: !2, file: !3, line: 75, type: !13, isLocal: false, isDefinition: true)
!108 = !DIGlobalVariableExpression(var: !109, expr: !DIExpression())
!109 = distinct !DIGlobalVariable(name: "__k_p4wq_initparam_area_load_start", scope: !2, file: !3, line: 76, type: !13, isLocal: false, isDefinition: true)
!110 = !DIGlobalVariableExpression(var: !111, expr: !DIExpression())
!111 = distinct !DIGlobalVariable(name: "__k_p4wq_initparam_area_end", scope: !2, file: !3, line: 78, type: !13, isLocal: false, isDefinition: true)
!112 = !DIGlobalVariableExpression(var: !113, expr: !DIExpression())
!113 = distinct !DIGlobalVariable(name: "_log_strings_list_start", scope: !2, file: !3, line: 79, type: !13, isLocal: false, isDefinition: true)
!114 = !DIGlobalVariableExpression(var: !115, expr: !DIExpression())
!115 = distinct !DIGlobalVariable(name: "_log_strings_list_end", scope: !2, file: !3, line: 80, type: !13, isLocal: false, isDefinition: true)
!116 = !DIGlobalVariableExpression(var: !117, expr: !DIExpression())
!117 = distinct !DIGlobalVariable(name: "__log_strings_area_start", scope: !2, file: !3, line: 81, type: !13, isLocal: false, isDefinition: true)
!118 = !DIGlobalVariableExpression(var: !119, expr: !DIExpression())
!119 = distinct !DIGlobalVariable(name: "__log_strings_area_load_start", scope: !2, file: !3, line: 82, type: !13, isLocal: false, isDefinition: true)
!120 = !DIGlobalVariableExpression(var: !121, expr: !DIExpression())
!121 = distinct !DIGlobalVariable(name: "__log_strings_area_end", scope: !2, file: !3, line: 84, type: !13, isLocal: false, isDefinition: true)
!122 = !DIGlobalVariableExpression(var: !123, expr: !DIExpression())
!123 = distinct !DIGlobalVariable(name: "_log_const_list_start", scope: !2, file: !3, line: 85, type: !13, isLocal: false, isDefinition: true)
!124 = !DIGlobalVariableExpression(var: !125, expr: !DIExpression())
!125 = distinct !DIGlobalVariable(name: "_log_const_list_end", scope: !2, file: !3, line: 86, type: !13, isLocal: false, isDefinition: true)
!126 = !DIGlobalVariableExpression(var: !127, expr: !DIExpression())
!127 = distinct !DIGlobalVariable(name: "__log_const_area_start", scope: !2, file: !3, line: 87, type: !13, isLocal: false, isDefinition: true)
!128 = !DIGlobalVariableExpression(var: !129, expr: !DIExpression())
!129 = distinct !DIGlobalVariable(name: "__log_const_area_load_start", scope: !2, file: !3, line: 88, type: !13, isLocal: false, isDefinition: true)
!130 = !DIGlobalVariableExpression(var: !131, expr: !DIExpression())
!131 = distinct !DIGlobalVariable(name: "__log_const_area_end", scope: !2, file: !3, line: 90, type: !13, isLocal: false, isDefinition: true)
!132 = !DIGlobalVariableExpression(var: !133, expr: !DIExpression())
!133 = distinct !DIGlobalVariable(name: "_shell_list_start", scope: !2, file: !3, line: 91, type: !13, isLocal: false, isDefinition: true)
!134 = !DIGlobalVariableExpression(var: !135, expr: !DIExpression())
!135 = distinct !DIGlobalVariable(name: "_shell_list_end", scope: !2, file: !3, line: 92, type: !13, isLocal: false, isDefinition: true)
!136 = !DIGlobalVariableExpression(var: !137, expr: !DIExpression())
!137 = distinct !DIGlobalVariable(name: "__shell_area_start", scope: !2, file: !3, line: 93, type: !13, isLocal: false, isDefinition: true)
!138 = !DIGlobalVariableExpression(var: !139, expr: !DIExpression())
!139 = distinct !DIGlobalVariable(name: "__shell_area_load_start", scope: !2, file: !3, line: 94, type: !13, isLocal: false, isDefinition: true)
!140 = !DIGlobalVariableExpression(var: !141, expr: !DIExpression())
!141 = distinct !DIGlobalVariable(name: "__shell_area_end", scope: !2, file: !3, line: 96, type: !13, isLocal: false, isDefinition: true)
!142 = !DIGlobalVariableExpression(var: !143, expr: !DIExpression())
!143 = distinct !DIGlobalVariable(name: "_shell_root_cmds_list_start", scope: !2, file: !3, line: 97, type: !13, isLocal: false, isDefinition: true)
!144 = !DIGlobalVariableExpression(var: !145, expr: !DIExpression())
!145 = distinct !DIGlobalVariable(name: "_shell_root_cmds_list_end", scope: !2, file: !3, line: 98, type: !13, isLocal: false, isDefinition: true)
!146 = !DIGlobalVariableExpression(var: !147, expr: !DIExpression())
!147 = distinct !DIGlobalVariable(name: "__shell_root_cmds_area_start", scope: !2, file: !3, line: 99, type: !13, isLocal: false, isDefinition: true)
!148 = !DIGlobalVariableExpression(var: !149, expr: !DIExpression())
!149 = distinct !DIGlobalVariable(name: "__shell_root_cmds_area_load_start", scope: !2, file: !3, line: 100, type: !13, isLocal: false, isDefinition: true)
!150 = !DIGlobalVariableExpression(var: !151, expr: !DIExpression())
!151 = distinct !DIGlobalVariable(name: "__shell_root_cmds_area_end", scope: !2, file: !3, line: 102, type: !13, isLocal: false, isDefinition: true)
!152 = !DIGlobalVariableExpression(var: !153, expr: !DIExpression())
!153 = distinct !DIGlobalVariable(name: "_shell_subcmds_list_start", scope: !2, file: !3, line: 103, type: !13, isLocal: false, isDefinition: true)
!154 = !DIGlobalVariableExpression(var: !155, expr: !DIExpression())
!155 = distinct !DIGlobalVariable(name: "_shell_subcmds_list_end", scope: !2, file: !3, line: 104, type: !13, isLocal: false, isDefinition: true)
!156 = !DIGlobalVariableExpression(var: !157, expr: !DIExpression())
!157 = distinct !DIGlobalVariable(name: "__shell_subcmds_area_start", scope: !2, file: !3, line: 105, type: !13, isLocal: false, isDefinition: true)
!158 = !DIGlobalVariableExpression(var: !159, expr: !DIExpression())
!159 = distinct !DIGlobalVariable(name: "__shell_subcmds_area_load_start", scope: !2, file: !3, line: 106, type: !13, isLocal: false, isDefinition: true)
!160 = !DIGlobalVariableExpression(var: !161, expr: !DIExpression())
!161 = distinct !DIGlobalVariable(name: "__shell_subcmds_area_end", scope: !2, file: !3, line: 108, type: !13, isLocal: false, isDefinition: true)
!162 = !DIGlobalVariableExpression(var: !163, expr: !DIExpression())
!163 = distinct !DIGlobalVariable(name: "_shell_dynamic_subcmds_list_start", scope: !2, file: !3, line: 109, type: !13, isLocal: false, isDefinition: true)
!164 = !DIGlobalVariableExpression(var: !165, expr: !DIExpression())
!165 = distinct !DIGlobalVariable(name: "_shell_dynamic_subcmds_list_end", scope: !2, file: !3, line: 110, type: !13, isLocal: false, isDefinition: true)
!166 = !DIGlobalVariableExpression(var: !167, expr: !DIExpression())
!167 = distinct !DIGlobalVariable(name: "__shell_dynamic_subcmds_area_start", scope: !2, file: !3, line: 111, type: !13, isLocal: false, isDefinition: true)
!168 = !DIGlobalVariableExpression(var: !169, expr: !DIExpression())
!169 = distinct !DIGlobalVariable(name: "__shell_dynamic_subcmds_area_load_start", scope: !2, file: !3, line: 112, type: !13, isLocal: false, isDefinition: true)
!170 = !DIGlobalVariableExpression(var: !171, expr: !DIExpression())
!171 = distinct !DIGlobalVariable(name: "__shell_dynamic_subcmds_area_end", scope: !2, file: !3, line: 114, type: !13, isLocal: false, isDefinition: true)
!172 = !DIGlobalVariableExpression(var: !173, expr: !DIExpression())
!173 = distinct !DIGlobalVariable(name: "_cfb_font_list_start", scope: !2, file: !3, line: 115, type: !13, isLocal: false, isDefinition: true)
!174 = !DIGlobalVariableExpression(var: !175, expr: !DIExpression())
!175 = distinct !DIGlobalVariable(name: "_cfb_font_list_end", scope: !2, file: !3, line: 116, type: !13, isLocal: false, isDefinition: true)
!176 = !DIGlobalVariableExpression(var: !177, expr: !DIExpression())
!177 = distinct !DIGlobalVariable(name: "__cfb_font_area_start", scope: !2, file: !3, line: 117, type: !13, isLocal: false, isDefinition: true)
!178 = !DIGlobalVariableExpression(var: !179, expr: !DIExpression())
!179 = distinct !DIGlobalVariable(name: "__cfb_font_area_load_start", scope: !2, file: !3, line: 118, type: !13, isLocal: false, isDefinition: true)
!180 = !DIGlobalVariableExpression(var: !181, expr: !DIExpression())
!181 = distinct !DIGlobalVariable(name: "__cfb_font_area_end", scope: !2, file: !3, line: 120, type: !13, isLocal: false, isDefinition: true)
!182 = !DIGlobalVariableExpression(var: !183, expr: !DIExpression())
!183 = distinct !DIGlobalVariable(name: "_tracing_backend_list_start", scope: !2, file: !3, line: 121, type: !13, isLocal: false, isDefinition: true)
!184 = !DIGlobalVariableExpression(var: !185, expr: !DIExpression())
!185 = distinct !DIGlobalVariable(name: "_tracing_backend_list_end", scope: !2, file: !3, line: 122, type: !13, isLocal: false, isDefinition: true)
!186 = !DIGlobalVariableExpression(var: !187, expr: !DIExpression())
!187 = distinct !DIGlobalVariable(name: "__tracing_backend_area_start", scope: !2, file: !3, line: 123, type: !13, isLocal: false, isDefinition: true)
!188 = !DIGlobalVariableExpression(var: !189, expr: !DIExpression())
!189 = distinct !DIGlobalVariable(name: "__tracing_backend_area_load_start", scope: !2, file: !3, line: 124, type: !13, isLocal: false, isDefinition: true)
!190 = !DIGlobalVariableExpression(var: !191, expr: !DIExpression())
!191 = distinct !DIGlobalVariable(name: "__tracing_backend_area_end", scope: !2, file: !3, line: 126, type: !13, isLocal: false, isDefinition: true)
!192 = !DIGlobalVariableExpression(var: !193, expr: !DIExpression())
!193 = distinct !DIGlobalVariable(name: "__zephyr_dbg_info_start", scope: !2, file: !3, line: 127, type: !13, isLocal: false, isDefinition: true)
!194 = !DIGlobalVariableExpression(var: !195, expr: !DIExpression())
!195 = distinct !DIGlobalVariable(name: "__zephyr_dbg_info_load_start", scope: !2, file: !3, line: 128, type: !13, isLocal: false, isDefinition: true)
!196 = !DIGlobalVariableExpression(var: !197, expr: !DIExpression())
!197 = distinct !DIGlobalVariable(name: "__zephyr_dbg_info_end", scope: !2, file: !3, line: 130, type: !13, isLocal: false, isDefinition: true)
!198 = !DIGlobalVariableExpression(var: !199, expr: !DIExpression())
!199 = distinct !DIGlobalVariable(name: "__zephyr_dbg_info_size", scope: !2, file: !3, line: 131, type: !13, isLocal: false, isDefinition: true)
!200 = !DIGlobalVariableExpression(var: !201, expr: !DIExpression())
!201 = distinct !DIGlobalVariable(name: "__static_thread_data_list_start", scope: !2, file: !3, line: 132, type: !13, isLocal: false, isDefinition: true)
!202 = !DIGlobalVariableExpression(var: !203, expr: !DIExpression())
!203 = distinct !DIGlobalVariable(name: "__static_thread_data_list_end", scope: !2, file: !3, line: 133, type: !13, isLocal: false, isDefinition: true)
!204 = !DIGlobalVariableExpression(var: !205, expr: !DIExpression())
!205 = distinct !DIGlobalVariable(name: "___static_thread_data_area_start", scope: !2, file: !3, line: 134, type: !13, isLocal: false, isDefinition: true)
!206 = !DIGlobalVariableExpression(var: !207, expr: !DIExpression())
!207 = distinct !DIGlobalVariable(name: "___static_thread_data_area_load_start", scope: !2, file: !3, line: 135, type: !13, isLocal: false, isDefinition: true)
!208 = !DIGlobalVariableExpression(var: !209, expr: !DIExpression())
!209 = distinct !DIGlobalVariable(name: "___static_thread_data_area_end", scope: !2, file: !3, line: 137, type: !13, isLocal: false, isDefinition: true)
!210 = !DIGlobalVariableExpression(var: !211, expr: !DIExpression())
!211 = distinct !DIGlobalVariable(name: "_log_link_list_start", scope: !2, file: !3, line: 138, type: !13, isLocal: false, isDefinition: true)
!212 = !DIGlobalVariableExpression(var: !213, expr: !DIExpression())
!213 = distinct !DIGlobalVariable(name: "_log_link_list_end", scope: !2, file: !3, line: 139, type: !13, isLocal: false, isDefinition: true)
!214 = !DIGlobalVariableExpression(var: !215, expr: !DIExpression())
!215 = distinct !DIGlobalVariable(name: "__log_link_area_start", scope: !2, file: !3, line: 140, type: !13, isLocal: false, isDefinition: true)
!216 = !DIGlobalVariableExpression(var: !217, expr: !DIExpression())
!217 = distinct !DIGlobalVariable(name: "__log_link_area_load_start", scope: !2, file: !3, line: 141, type: !13, isLocal: false, isDefinition: true)
!218 = !DIGlobalVariableExpression(var: !219, expr: !DIExpression())
!219 = distinct !DIGlobalVariable(name: "__log_link_area_end", scope: !2, file: !3, line: 143, type: !13, isLocal: false, isDefinition: true)
!220 = !DIGlobalVariableExpression(var: !221, expr: !DIExpression())
!221 = distinct !DIGlobalVariable(name: "_log_backend_list_start", scope: !2, file: !3, line: 144, type: !13, isLocal: false, isDefinition: true)
!222 = !DIGlobalVariableExpression(var: !223, expr: !DIExpression())
!223 = distinct !DIGlobalVariable(name: "_log_backend_list_end", scope: !2, file: !3, line: 145, type: !13, isLocal: false, isDefinition: true)
!224 = !DIGlobalVariableExpression(var: !225, expr: !DIExpression())
!225 = distinct !DIGlobalVariable(name: "__log_backend_area_start", scope: !2, file: !3, line: 146, type: !13, isLocal: false, isDefinition: true)
!226 = !DIGlobalVariableExpression(var: !227, expr: !DIExpression())
!227 = distinct !DIGlobalVariable(name: "__log_backend_area_load_start", scope: !2, file: !3, line: 147, type: !13, isLocal: false, isDefinition: true)
!228 = !DIGlobalVariableExpression(var: !229, expr: !DIExpression())
!229 = distinct !DIGlobalVariable(name: "__log_backend_area_end", scope: !2, file: !3, line: 149, type: !13, isLocal: false, isDefinition: true)
!230 = !DIGlobalVariableExpression(var: !231, expr: !DIExpression())
!231 = distinct !DIGlobalVariable(name: "__rodata_start", scope: !2, file: !3, line: 150, type: !13, isLocal: false, isDefinition: true)
!232 = !DIGlobalVariableExpression(var: !233, expr: !DIExpression())
!233 = distinct !DIGlobalVariable(name: "__rodata_load_start", scope: !2, file: !3, line: 151, type: !13, isLocal: false, isDefinition: true)
!234 = !DIGlobalVariableExpression(var: !235, expr: !DIExpression())
!235 = distinct !DIGlobalVariable(name: "__rodata_end", scope: !2, file: !3, line: 153, type: !13, isLocal: false, isDefinition: true)
!236 = !DIGlobalVariableExpression(var: !237, expr: !DIExpression())
!237 = distinct !DIGlobalVariable(name: "__rodata_size", scope: !2, file: !3, line: 154, type: !13, isLocal: false, isDefinition: true)
!238 = !DIGlobalVariableExpression(var: !239, expr: !DIExpression())
!239 = distinct !DIGlobalVariable(name: "__ARM_exidx_start", scope: !2, file: !3, line: 155, type: !13, isLocal: false, isDefinition: true)
!240 = !DIGlobalVariableExpression(var: !241, expr: !DIExpression())
!241 = distinct !DIGlobalVariable(name: "__ARM_exidx_load_start", scope: !2, file: !3, line: 156, type: !13, isLocal: false, isDefinition: true)
!242 = !DIGlobalVariableExpression(var: !243, expr: !DIExpression())
!243 = distinct !DIGlobalVariable(name: "__ARM_exidx_end", scope: !2, file: !3, line: 158, type: !13, isLocal: false, isDefinition: true)
!244 = !DIGlobalVariableExpression(var: !245, expr: !DIExpression())
!245 = distinct !DIGlobalVariable(name: "__ARM_exidx_size", scope: !2, file: !3, line: 159, type: !13, isLocal: false, isDefinition: true)
!246 = !DIGlobalVariableExpression(var: !247, expr: !DIExpression())
!247 = distinct !DIGlobalVariable(name: "__data_load_start", scope: !2, file: !3, line: 160, type: !13, isLocal: false, isDefinition: true)
!248 = !DIGlobalVariableExpression(var: !249, expr: !DIExpression())
!249 = distinct !DIGlobalVariable(name: "__data_end", scope: !2, file: !3, line: 162, type: !13, isLocal: false, isDefinition: true)
!250 = !DIGlobalVariableExpression(var: !251, expr: !DIExpression())
!251 = distinct !DIGlobalVariable(name: "__data_size", scope: !2, file: !3, line: 163, type: !13, isLocal: false, isDefinition: true)
!252 = !DIGlobalVariableExpression(var: !253, expr: !DIExpression())
!253 = distinct !DIGlobalVariable(name: "__device_states_start", scope: !2, file: !3, line: 164, type: !13, isLocal: false, isDefinition: true)
!254 = !DIGlobalVariableExpression(var: !255, expr: !DIExpression())
!255 = distinct !DIGlobalVariable(name: "__device_states_load_start", scope: !2, file: !3, line: 165, type: !13, isLocal: false, isDefinition: true)
!256 = !DIGlobalVariableExpression(var: !257, expr: !DIExpression())
!257 = distinct !DIGlobalVariable(name: "__device_states_end", scope: !2, file: !3, line: 167, type: !13, isLocal: false, isDefinition: true)
!258 = !DIGlobalVariableExpression(var: !259, expr: !DIExpression())
!259 = distinct !DIGlobalVariable(name: "__device_states_size", scope: !2, file: !3, line: 168, type: !13, isLocal: false, isDefinition: true)
!260 = !DIGlobalVariableExpression(var: !261, expr: !DIExpression())
!261 = distinct !DIGlobalVariable(name: "_log_dynamic_list_start", scope: !2, file: !3, line: 169, type: !13, isLocal: false, isDefinition: true)
!262 = !DIGlobalVariableExpression(var: !263, expr: !DIExpression())
!263 = distinct !DIGlobalVariable(name: "_log_dynamic_list_end", scope: !2, file: !3, line: 170, type: !13, isLocal: false, isDefinition: true)
!264 = !DIGlobalVariableExpression(var: !265, expr: !DIExpression())
!265 = distinct !DIGlobalVariable(name: "__log_dynamic_area_start", scope: !2, file: !3, line: 171, type: !13, isLocal: false, isDefinition: true)
!266 = !DIGlobalVariableExpression(var: !267, expr: !DIExpression())
!267 = distinct !DIGlobalVariable(name: "__log_dynamic_area_load_start", scope: !2, file: !3, line: 172, type: !13, isLocal: false, isDefinition: true)
!268 = !DIGlobalVariableExpression(var: !269, expr: !DIExpression())
!269 = distinct !DIGlobalVariable(name: "__log_dynamic_area_end", scope: !2, file: !3, line: 174, type: !13, isLocal: false, isDefinition: true)
!270 = !DIGlobalVariableExpression(var: !271, expr: !DIExpression())
!271 = distinct !DIGlobalVariable(name: "_k_timer_list_start", scope: !2, file: !3, line: 175, type: !13, isLocal: false, isDefinition: true)
!272 = !DIGlobalVariableExpression(var: !273, expr: !DIExpression())
!273 = distinct !DIGlobalVariable(name: "_k_timer_list_end", scope: !2, file: !3, line: 176, type: !13, isLocal: false, isDefinition: true)
!274 = !DIGlobalVariableExpression(var: !275, expr: !DIExpression())
!275 = distinct !DIGlobalVariable(name: "__k_timer_area_start", scope: !2, file: !3, line: 177, type: !13, isLocal: false, isDefinition: true)
!276 = !DIGlobalVariableExpression(var: !277, expr: !DIExpression())
!277 = distinct !DIGlobalVariable(name: "__k_timer_area_load_start", scope: !2, file: !3, line: 178, type: !13, isLocal: false, isDefinition: true)
!278 = !DIGlobalVariableExpression(var: !279, expr: !DIExpression())
!279 = distinct !DIGlobalVariable(name: "__k_timer_area_end", scope: !2, file: !3, line: 180, type: !13, isLocal: false, isDefinition: true)
!280 = !DIGlobalVariableExpression(var: !281, expr: !DIExpression())
!281 = distinct !DIGlobalVariable(name: "_k_mem_slab_list_start", scope: !2, file: !3, line: 181, type: !13, isLocal: false, isDefinition: true)
!282 = !DIGlobalVariableExpression(var: !283, expr: !DIExpression())
!283 = distinct !DIGlobalVariable(name: "_k_mem_slab_list_end", scope: !2, file: !3, line: 182, type: !13, isLocal: false, isDefinition: true)
!284 = !DIGlobalVariableExpression(var: !285, expr: !DIExpression())
!285 = distinct !DIGlobalVariable(name: "__k_mem_slab_area_start", scope: !2, file: !3, line: 183, type: !13, isLocal: false, isDefinition: true)
!286 = !DIGlobalVariableExpression(var: !287, expr: !DIExpression())
!287 = distinct !DIGlobalVariable(name: "__k_mem_slab_area_load_start", scope: !2, file: !3, line: 184, type: !13, isLocal: false, isDefinition: true)
!288 = !DIGlobalVariableExpression(var: !289, expr: !DIExpression())
!289 = distinct !DIGlobalVariable(name: "__k_mem_slab_area_end", scope: !2, file: !3, line: 186, type: !13, isLocal: false, isDefinition: true)
!290 = !DIGlobalVariableExpression(var: !291, expr: !DIExpression())
!291 = distinct !DIGlobalVariable(name: "_k_heap_list_start", scope: !2, file: !3, line: 187, type: !13, isLocal: false, isDefinition: true)
!292 = !DIGlobalVariableExpression(var: !293, expr: !DIExpression())
!293 = distinct !DIGlobalVariable(name: "_k_heap_list_end", scope: !2, file: !3, line: 188, type: !13, isLocal: false, isDefinition: true)
!294 = !DIGlobalVariableExpression(var: !295, expr: !DIExpression())
!295 = distinct !DIGlobalVariable(name: "__k_heap_area_start", scope: !2, file: !3, line: 189, type: !13, isLocal: false, isDefinition: true)
!296 = !DIGlobalVariableExpression(var: !297, expr: !DIExpression())
!297 = distinct !DIGlobalVariable(name: "__k_heap_area_load_start", scope: !2, file: !3, line: 190, type: !13, isLocal: false, isDefinition: true)
!298 = !DIGlobalVariableExpression(var: !299, expr: !DIExpression())
!299 = distinct !DIGlobalVariable(name: "__k_heap_area_end", scope: !2, file: !3, line: 192, type: !13, isLocal: false, isDefinition: true)
!300 = !DIGlobalVariableExpression(var: !301, expr: !DIExpression())
!301 = distinct !DIGlobalVariable(name: "_k_mutex_list_start", scope: !2, file: !3, line: 193, type: !13, isLocal: false, isDefinition: true)
!302 = !DIGlobalVariableExpression(var: !303, expr: !DIExpression())
!303 = distinct !DIGlobalVariable(name: "_k_mutex_list_end", scope: !2, file: !3, line: 194, type: !13, isLocal: false, isDefinition: true)
!304 = !DIGlobalVariableExpression(var: !305, expr: !DIExpression())
!305 = distinct !DIGlobalVariable(name: "__k_mutex_area_start", scope: !2, file: !3, line: 195, type: !13, isLocal: false, isDefinition: true)
!306 = !DIGlobalVariableExpression(var: !307, expr: !DIExpression())
!307 = distinct !DIGlobalVariable(name: "__k_mutex_area_load_start", scope: !2, file: !3, line: 196, type: !13, isLocal: false, isDefinition: true)
!308 = !DIGlobalVariableExpression(var: !309, expr: !DIExpression())
!309 = distinct !DIGlobalVariable(name: "__k_mutex_area_end", scope: !2, file: !3, line: 198, type: !13, isLocal: false, isDefinition: true)
!310 = !DIGlobalVariableExpression(var: !311, expr: !DIExpression())
!311 = distinct !DIGlobalVariable(name: "_k_stack_list_start", scope: !2, file: !3, line: 199, type: !13, isLocal: false, isDefinition: true)
!312 = !DIGlobalVariableExpression(var: !313, expr: !DIExpression())
!313 = distinct !DIGlobalVariable(name: "_k_stack_list_end", scope: !2, file: !3, line: 200, type: !13, isLocal: false, isDefinition: true)
!314 = !DIGlobalVariableExpression(var: !315, expr: !DIExpression())
!315 = distinct !DIGlobalVariable(name: "__k_stack_area_start", scope: !2, file: !3, line: 201, type: !13, isLocal: false, isDefinition: true)
!316 = !DIGlobalVariableExpression(var: !317, expr: !DIExpression())
!317 = distinct !DIGlobalVariable(name: "__k_stack_area_load_start", scope: !2, file: !3, line: 202, type: !13, isLocal: false, isDefinition: true)
!318 = !DIGlobalVariableExpression(var: !319, expr: !DIExpression())
!319 = distinct !DIGlobalVariable(name: "__k_stack_area_end", scope: !2, file: !3, line: 204, type: !13, isLocal: false, isDefinition: true)
!320 = !DIGlobalVariableExpression(var: !321, expr: !DIExpression())
!321 = distinct !DIGlobalVariable(name: "_k_msgq_list_start", scope: !2, file: !3, line: 205, type: !13, isLocal: false, isDefinition: true)
!322 = !DIGlobalVariableExpression(var: !323, expr: !DIExpression())
!323 = distinct !DIGlobalVariable(name: "_k_msgq_list_end", scope: !2, file: !3, line: 206, type: !13, isLocal: false, isDefinition: true)
!324 = !DIGlobalVariableExpression(var: !325, expr: !DIExpression())
!325 = distinct !DIGlobalVariable(name: "__k_msgq_area_start", scope: !2, file: !3, line: 207, type: !13, isLocal: false, isDefinition: true)
!326 = !DIGlobalVariableExpression(var: !327, expr: !DIExpression())
!327 = distinct !DIGlobalVariable(name: "__k_msgq_area_load_start", scope: !2, file: !3, line: 208, type: !13, isLocal: false, isDefinition: true)
!328 = !DIGlobalVariableExpression(var: !329, expr: !DIExpression())
!329 = distinct !DIGlobalVariable(name: "__k_msgq_area_end", scope: !2, file: !3, line: 210, type: !13, isLocal: false, isDefinition: true)
!330 = !DIGlobalVariableExpression(var: !331, expr: !DIExpression())
!331 = distinct !DIGlobalVariable(name: "_k_mbox_list_start", scope: !2, file: !3, line: 211, type: !13, isLocal: false, isDefinition: true)
!332 = !DIGlobalVariableExpression(var: !333, expr: !DIExpression())
!333 = distinct !DIGlobalVariable(name: "_k_mbox_list_end", scope: !2, file: !3, line: 212, type: !13, isLocal: false, isDefinition: true)
!334 = !DIGlobalVariableExpression(var: !335, expr: !DIExpression())
!335 = distinct !DIGlobalVariable(name: "__k_mbox_area_start", scope: !2, file: !3, line: 213, type: !13, isLocal: false, isDefinition: true)
!336 = !DIGlobalVariableExpression(var: !337, expr: !DIExpression())
!337 = distinct !DIGlobalVariable(name: "__k_mbox_area_load_start", scope: !2, file: !3, line: 214, type: !13, isLocal: false, isDefinition: true)
!338 = !DIGlobalVariableExpression(var: !339, expr: !DIExpression())
!339 = distinct !DIGlobalVariable(name: "__k_mbox_area_end", scope: !2, file: !3, line: 216, type: !13, isLocal: false, isDefinition: true)
!340 = !DIGlobalVariableExpression(var: !341, expr: !DIExpression())
!341 = distinct !DIGlobalVariable(name: "_k_pipe_list_start", scope: !2, file: !3, line: 217, type: !13, isLocal: false, isDefinition: true)
!342 = !DIGlobalVariableExpression(var: !343, expr: !DIExpression())
!343 = distinct !DIGlobalVariable(name: "_k_pipe_list_end", scope: !2, file: !3, line: 218, type: !13, isLocal: false, isDefinition: true)
!344 = !DIGlobalVariableExpression(var: !345, expr: !DIExpression())
!345 = distinct !DIGlobalVariable(name: "__k_pipe_area_start", scope: !2, file: !3, line: 219, type: !13, isLocal: false, isDefinition: true)
!346 = !DIGlobalVariableExpression(var: !347, expr: !DIExpression())
!347 = distinct !DIGlobalVariable(name: "__k_pipe_area_load_start", scope: !2, file: !3, line: 220, type: !13, isLocal: false, isDefinition: true)
!348 = !DIGlobalVariableExpression(var: !349, expr: !DIExpression())
!349 = distinct !DIGlobalVariable(name: "__k_pipe_area_end", scope: !2, file: !3, line: 222, type: !13, isLocal: false, isDefinition: true)
!350 = !DIGlobalVariableExpression(var: !351, expr: !DIExpression())
!351 = distinct !DIGlobalVariable(name: "_k_sem_list_start", scope: !2, file: !3, line: 223, type: !13, isLocal: false, isDefinition: true)
!352 = !DIGlobalVariableExpression(var: !353, expr: !DIExpression())
!353 = distinct !DIGlobalVariable(name: "_k_sem_list_end", scope: !2, file: !3, line: 224, type: !13, isLocal: false, isDefinition: true)
!354 = !DIGlobalVariableExpression(var: !355, expr: !DIExpression())
!355 = distinct !DIGlobalVariable(name: "__k_sem_area_start", scope: !2, file: !3, line: 225, type: !13, isLocal: false, isDefinition: true)
!356 = !DIGlobalVariableExpression(var: !357, expr: !DIExpression())
!357 = distinct !DIGlobalVariable(name: "__k_sem_area_load_start", scope: !2, file: !3, line: 226, type: !13, isLocal: false, isDefinition: true)
!358 = !DIGlobalVariableExpression(var: !359, expr: !DIExpression())
!359 = distinct !DIGlobalVariable(name: "__k_sem_area_end", scope: !2, file: !3, line: 228, type: !13, isLocal: false, isDefinition: true)
!360 = !DIGlobalVariableExpression(var: !361, expr: !DIExpression())
!361 = distinct !DIGlobalVariable(name: "_k_queue_list_start", scope: !2, file: !3, line: 229, type: !13, isLocal: false, isDefinition: true)
!362 = !DIGlobalVariableExpression(var: !363, expr: !DIExpression())
!363 = distinct !DIGlobalVariable(name: "_k_queue_list_end", scope: !2, file: !3, line: 230, type: !13, isLocal: false, isDefinition: true)
!364 = !DIGlobalVariableExpression(var: !365, expr: !DIExpression())
!365 = distinct !DIGlobalVariable(name: "__k_queue_area_start", scope: !2, file: !3, line: 231, type: !13, isLocal: false, isDefinition: true)
!366 = !DIGlobalVariableExpression(var: !367, expr: !DIExpression())
!367 = distinct !DIGlobalVariable(name: "__k_queue_area_load_start", scope: !2, file: !3, line: 232, type: !13, isLocal: false, isDefinition: true)
!368 = !DIGlobalVariableExpression(var: !369, expr: !DIExpression())
!369 = distinct !DIGlobalVariable(name: "__k_queue_area_end", scope: !2, file: !3, line: 234, type: !13, isLocal: false, isDefinition: true)
!370 = !DIGlobalVariableExpression(var: !371, expr: !DIExpression())
!371 = distinct !DIGlobalVariable(name: "_k_condvar_list_start", scope: !2, file: !3, line: 235, type: !13, isLocal: false, isDefinition: true)
!372 = !DIGlobalVariableExpression(var: !373, expr: !DIExpression())
!373 = distinct !DIGlobalVariable(name: "_k_condvar_list_end", scope: !2, file: !3, line: 236, type: !13, isLocal: false, isDefinition: true)
!374 = !DIGlobalVariableExpression(var: !375, expr: !DIExpression())
!375 = distinct !DIGlobalVariable(name: "__k_condvar_area_start", scope: !2, file: !3, line: 237, type: !13, isLocal: false, isDefinition: true)
!376 = !DIGlobalVariableExpression(var: !377, expr: !DIExpression())
!377 = distinct !DIGlobalVariable(name: "__k_condvar_area_load_start", scope: !2, file: !3, line: 238, type: !13, isLocal: false, isDefinition: true)
!378 = !DIGlobalVariableExpression(var: !379, expr: !DIExpression())
!379 = distinct !DIGlobalVariable(name: "__k_condvar_area_end", scope: !2, file: !3, line: 240, type: !13, isLocal: false, isDefinition: true)
!380 = !DIGlobalVariableExpression(var: !381, expr: !DIExpression())
!381 = distinct !DIGlobalVariable(name: "_k_event_list_start", scope: !2, file: !3, line: 241, type: !13, isLocal: false, isDefinition: true)
!382 = !DIGlobalVariableExpression(var: !383, expr: !DIExpression())
!383 = distinct !DIGlobalVariable(name: "_k_event_list_end", scope: !2, file: !3, line: 242, type: !13, isLocal: false, isDefinition: true)
!384 = !DIGlobalVariableExpression(var: !385, expr: !DIExpression())
!385 = distinct !DIGlobalVariable(name: "__k_event_area_start", scope: !2, file: !3, line: 243, type: !13, isLocal: false, isDefinition: true)
!386 = !DIGlobalVariableExpression(var: !387, expr: !DIExpression())
!387 = distinct !DIGlobalVariable(name: "__k_event_area_load_start", scope: !2, file: !3, line: 244, type: !13, isLocal: false, isDefinition: true)
!388 = !DIGlobalVariableExpression(var: !389, expr: !DIExpression())
!389 = distinct !DIGlobalVariable(name: "__k_event_area_end", scope: !2, file: !3, line: 246, type: !13, isLocal: false, isDefinition: true)
!390 = !DIGlobalVariableExpression(var: !391, expr: !DIExpression())
!391 = distinct !DIGlobalVariable(name: "_net_buf_pool_list_start", scope: !2, file: !3, line: 247, type: !13, isLocal: false, isDefinition: true)
!392 = !DIGlobalVariableExpression(var: !393, expr: !DIExpression())
!393 = distinct !DIGlobalVariable(name: "_net_buf_pool_list_end", scope: !2, file: !3, line: 248, type: !13, isLocal: false, isDefinition: true)
!394 = !DIGlobalVariableExpression(var: !395, expr: !DIExpression())
!395 = distinct !DIGlobalVariable(name: "__net_buf_pool_area_start", scope: !2, file: !3, line: 249, type: !13, isLocal: false, isDefinition: true)
!396 = !DIGlobalVariableExpression(var: !397, expr: !DIExpression())
!397 = distinct !DIGlobalVariable(name: "__net_buf_pool_area_load_start", scope: !2, file: !3, line: 250, type: !13, isLocal: false, isDefinition: true)
!398 = !DIGlobalVariableExpression(var: !399, expr: !DIExpression())
!399 = distinct !DIGlobalVariable(name: "__net_buf_pool_area_end", scope: !2, file: !3, line: 252, type: !13, isLocal: false, isDefinition: true)
!400 = !DIGlobalVariableExpression(var: !401, expr: !DIExpression())
!401 = distinct !DIGlobalVariable(name: "_log_mpsc_pbuf_list_start", scope: !2, file: !3, line: 253, type: !13, isLocal: false, isDefinition: true)
!402 = !DIGlobalVariableExpression(var: !403, expr: !DIExpression())
!403 = distinct !DIGlobalVariable(name: "_log_mpsc_pbuf_list_end", scope: !2, file: !3, line: 254, type: !13, isLocal: false, isDefinition: true)
!404 = !DIGlobalVariableExpression(var: !405, expr: !DIExpression())
!405 = distinct !DIGlobalVariable(name: "__log_mpsc_pbuf_area_start", scope: !2, file: !3, line: 255, type: !13, isLocal: false, isDefinition: true)
!406 = !DIGlobalVariableExpression(var: !407, expr: !DIExpression())
!407 = distinct !DIGlobalVariable(name: "__log_mpsc_pbuf_area_load_start", scope: !2, file: !3, line: 256, type: !13, isLocal: false, isDefinition: true)
!408 = !DIGlobalVariableExpression(var: !409, expr: !DIExpression())
!409 = distinct !DIGlobalVariable(name: "__log_mpsc_pbuf_area_end", scope: !2, file: !3, line: 258, type: !13, isLocal: false, isDefinition: true)
!410 = !DIGlobalVariableExpression(var: !411, expr: !DIExpression())
!411 = distinct !DIGlobalVariable(name: "_log_msg_ptr_list_start", scope: !2, file: !3, line: 259, type: !13, isLocal: false, isDefinition: true)
!412 = !DIGlobalVariableExpression(var: !413, expr: !DIExpression())
!413 = distinct !DIGlobalVariable(name: "_log_msg_ptr_list_end", scope: !2, file: !3, line: 260, type: !13, isLocal: false, isDefinition: true)
!414 = !DIGlobalVariableExpression(var: !415, expr: !DIExpression())
!415 = distinct !DIGlobalVariable(name: "__log_msg_ptr_area_start", scope: !2, file: !3, line: 261, type: !13, isLocal: false, isDefinition: true)
!416 = !DIGlobalVariableExpression(var: !417, expr: !DIExpression())
!417 = distinct !DIGlobalVariable(name: "__log_msg_ptr_area_load_start", scope: !2, file: !3, line: 262, type: !13, isLocal: false, isDefinition: true)
!418 = !DIGlobalVariableExpression(var: !419, expr: !DIExpression())
!419 = distinct !DIGlobalVariable(name: "__log_msg_ptr_area_end", scope: !2, file: !3, line: 264, type: !13, isLocal: false, isDefinition: true)
!420 = !DIGlobalVariableExpression(var: !421, expr: !DIExpression())
!421 = distinct !DIGlobalVariable(name: "__ramfunc_start", scope: !2, file: !3, line: 265, type: !13, isLocal: false, isDefinition: true)
!422 = !DIGlobalVariableExpression(var: !423, expr: !DIExpression())
!423 = distinct !DIGlobalVariable(name: "__ramfunc_load_start", scope: !2, file: !3, line: 266, type: !13, isLocal: false, isDefinition: true)
!424 = !DIGlobalVariableExpression(var: !425, expr: !DIExpression())
!425 = distinct !DIGlobalVariable(name: "__ramfunc_end", scope: !2, file: !3, line: 268, type: !13, isLocal: false, isDefinition: true)
!426 = !DIGlobalVariableExpression(var: !427, expr: !DIExpression())
!427 = distinct !DIGlobalVariable(name: "__ramfunc_size", scope: !2, file: !3, line: 269, type: !13, isLocal: false, isDefinition: true)
!428 = !DIGlobalVariableExpression(var: !429, expr: !DIExpression())
!429 = distinct !DIGlobalVariable(name: "__noinit_start", scope: !2, file: !3, line: 270, type: !13, isLocal: false, isDefinition: true)
!430 = !DIGlobalVariableExpression(var: !431, expr: !DIExpression())
!431 = distinct !DIGlobalVariable(name: "__noinit_load_start", scope: !2, file: !3, line: 271, type: !13, isLocal: false, isDefinition: true)
!432 = !DIGlobalVariableExpression(var: !433, expr: !DIExpression())
!433 = distinct !DIGlobalVariable(name: "__noinit_end", scope: !2, file: !3, line: 273, type: !13, isLocal: false, isDefinition: true)
!434 = !DIGlobalVariableExpression(var: !435, expr: !DIExpression())
!435 = distinct !DIGlobalVariable(name: "__noinit_size", scope: !2, file: !3, line: 274, type: !13, isLocal: false, isDefinition: true)
!436 = !DIGlobalVariableExpression(var: !437, expr: !DIExpression())
!437 = distinct !DIGlobalVariable(name: "__bss_start", scope: !2, file: !3, line: 275, type: !13, isLocal: false, isDefinition: true)
!438 = !DIGlobalVariableExpression(var: !439, expr: !DIExpression())
!439 = distinct !DIGlobalVariable(name: "__bss_load_start", scope: !2, file: !3, line: 276, type: !13, isLocal: false, isDefinition: true)
!440 = !DIGlobalVariableExpression(var: !441, expr: !DIExpression())
!441 = distinct !DIGlobalVariable(name: "__bss_end", scope: !2, file: !3, line: 278, type: !13, isLocal: false, isDefinition: true)
!442 = !DIGlobalVariableExpression(var: !443, expr: !DIExpression())
!443 = distinct !DIGlobalVariable(name: "__bss_size", scope: !2, file: !3, line: 279, type: !13, isLocal: false, isDefinition: true)
!444 = !DIGlobalVariableExpression(var: !445, expr: !DIExpression())
!445 = distinct !DIGlobalVariable(name: "__last_ram_section_start", scope: !2, file: !3, line: 280, type: !13, isLocal: false, isDefinition: true)
!446 = !DIGlobalVariableExpression(var: !447, expr: !DIExpression())
!447 = distinct !DIGlobalVariable(name: "__last_ram_section_load_start", scope: !2, file: !3, line: 281, type: !13, isLocal: false, isDefinition: true)
!448 = !DIGlobalVariableExpression(var: !449, expr: !DIExpression())
!449 = distinct !DIGlobalVariable(name: "__last_ram_section_end", scope: !2, file: !3, line: 283, type: !13, isLocal: false, isDefinition: true)
!450 = !DIGlobalVariableExpression(var: !451, expr: !DIExpression())
!451 = distinct !DIGlobalVariable(name: "__last_ram_section_size", scope: !2, file: !3, line: 284, type: !13, isLocal: false, isDefinition: true)
!452 = !DIGlobalVariableExpression(var: !453, expr: !DIExpression())
!453 = distinct !DIGlobalVariable(name: "__rom_region_start", scope: !2, file: !3, line: 285, type: !13, isLocal: false, isDefinition: true)
!454 = !DIGlobalVariableExpression(var: !455, expr: !DIExpression())
!455 = distinct !DIGlobalVariable(name: "__rom_region_load_start", scope: !2, file: !3, line: 287, type: !13, isLocal: false, isDefinition: true)
!456 = !DIGlobalVariableExpression(var: !457, expr: !DIExpression())
!457 = distinct !DIGlobalVariable(name: "__rom_region_end", scope: !2, file: !3, line: 289, type: !13, isLocal: false, isDefinition: true)
!458 = !DIGlobalVariableExpression(var: !459, expr: !DIExpression())
!459 = distinct !DIGlobalVariable(name: "__text_region_start", scope: !2, file: !3, line: 290, type: !13, isLocal: false, isDefinition: true)
!460 = !DIGlobalVariableExpression(var: !461, expr: !DIExpression())
!461 = distinct !DIGlobalVariable(name: "__text_region_load_start", scope: !2, file: !3, line: 292, type: !13, isLocal: false, isDefinition: true)
!462 = !DIGlobalVariableExpression(var: !463, expr: !DIExpression())
!463 = distinct !DIGlobalVariable(name: "__text_region_end", scope: !2, file: !3, line: 294, type: !13, isLocal: false, isDefinition: true)
!464 = !DIGlobalVariableExpression(var: !465, expr: !DIExpression())
!465 = distinct !DIGlobalVariable(name: "__rodata_region_start", scope: !2, file: !3, line: 295, type: !13, isLocal: false, isDefinition: true)
!466 = !DIGlobalVariableExpression(var: !467, expr: !DIExpression())
!467 = distinct !DIGlobalVariable(name: "__rodata_region_load_start", scope: !2, file: !3, line: 297, type: !13, isLocal: false, isDefinition: true)
!468 = !DIGlobalVariableExpression(var: !469, expr: !DIExpression())
!469 = distinct !DIGlobalVariable(name: "__rodata_region_end", scope: !2, file: !3, line: 299, type: !13, isLocal: false, isDefinition: true)
!470 = !DIGlobalVariableExpression(var: !471, expr: !DIExpression())
!471 = distinct !DIGlobalVariable(name: "__ram_region_start", scope: !2, file: !3, line: 300, type: !13, isLocal: false, isDefinition: true)
!472 = !DIGlobalVariableExpression(var: !473, expr: !DIExpression())
!473 = distinct !DIGlobalVariable(name: "__ram_region_load_start", scope: !2, file: !3, line: 302, type: !13, isLocal: false, isDefinition: true)
!474 = !DIGlobalVariableExpression(var: !475, expr: !DIExpression())
!475 = distinct !DIGlobalVariable(name: "__ram_region_end", scope: !2, file: !3, line: 304, type: !13, isLocal: false, isDefinition: true)
!476 = !DIGlobalVariableExpression(var: !477, expr: !DIExpression())
!477 = distinct !DIGlobalVariable(name: "__data_region_start", scope: !2, file: !3, line: 305, type: !13, isLocal: false, isDefinition: true)
!478 = !DIGlobalVariableExpression(var: !479, expr: !DIExpression())
!479 = distinct !DIGlobalVariable(name: "__data_region_load_start", scope: !2, file: !3, line: 307, type: !13, isLocal: false, isDefinition: true)
!480 = !DIGlobalVariableExpression(var: !481, expr: !DIExpression())
!481 = distinct !DIGlobalVariable(name: "__data_region_end", scope: !2, file: !3, line: 309, type: !13, isLocal: false, isDefinition: true)
!482 = !DIGlobalVariableExpression(var: !483, expr: !DIExpression())
!483 = distinct !DIGlobalVariable(name: "__kernel_ram_start", scope: !2, file: !3, line: 310, type: !13, isLocal: false, isDefinition: true)
!484 = !DIGlobalVariableExpression(var: !485, expr: !DIExpression())
!485 = distinct !DIGlobalVariable(name: "__kernel_ram_end", scope: !2, file: !3, line: 311, type: !13, isLocal: false, isDefinition: true)
!486 = !DIGlobalVariableExpression(var: !487, expr: !DIExpression())
!487 = distinct !DIGlobalVariable(name: "__kernel_ram_size", scope: !2, file: !3, line: 312, type: !13, isLocal: false, isDefinition: true)
!488 = !DIGlobalVariableExpression(var: !489, expr: !DIExpression())
!489 = distinct !DIGlobalVariable(name: "_image_ram_start", scope: !2, file: !3, line: 313, type: !13, isLocal: false, isDefinition: true)
!490 = !DIGlobalVariableExpression(var: !491, expr: !DIExpression())
!491 = distinct !DIGlobalVariable(name: "ARM_LIB_STACKHEAP", scope: !2, file: !3, line: 314, type: !13, isLocal: false, isDefinition: true)
!492 = !DIGlobalVariableExpression(var: !493, expr: !DIExpression())
!493 = distinct !DIGlobalVariable(name: "__init_size", scope: !2, file: !3, line: 315, type: !13, isLocal: false, isDefinition: true)
!494 = !DIGlobalVariableExpression(var: !495, expr: !DIExpression())
!495 = distinct !DIGlobalVariable(name: "__device_area_size", scope: !2, file: !3, line: 316, type: !13, isLocal: false, isDefinition: true)
!496 = !DIGlobalVariableExpression(var: !497, expr: !DIExpression())
!497 = distinct !DIGlobalVariable(name: "__initlevel_error_size", scope: !2, file: !3, line: 317, type: !13, isLocal: false, isDefinition: true)
!498 = !DIGlobalVariableExpression(var: !499, expr: !DIExpression())
!499 = distinct !DIGlobalVariable(name: "__app_shmem_regions_size", scope: !2, file: !3, line: 318, type: !13, isLocal: false, isDefinition: true)
!500 = !DIGlobalVariableExpression(var: !501, expr: !DIExpression())
!501 = distinct !DIGlobalVariable(name: "__bt_l2cap_fixed_chan_area_size", scope: !2, file: !3, line: 319, type: !13, isLocal: false, isDefinition: true)
!502 = !DIGlobalVariableExpression(var: !503, expr: !DIExpression())
!503 = distinct !DIGlobalVariable(name: "__bt_gatt_service_static_area_size", scope: !2, file: !3, line: 320, type: !13, isLocal: false, isDefinition: true)
!504 = !DIGlobalVariableExpression(var: !505, expr: !DIExpression())
!505 = distinct !DIGlobalVariable(name: "__k_p4wq_initparam_area_size", scope: !2, file: !3, line: 321, type: !13, isLocal: false, isDefinition: true)
!506 = !DIGlobalVariableExpression(var: !507, expr: !DIExpression())
!507 = distinct !DIGlobalVariable(name: "__log_strings_area_size", scope: !2, file: !3, line: 322, type: !13, isLocal: false, isDefinition: true)
!508 = !DIGlobalVariableExpression(var: !509, expr: !DIExpression())
!509 = distinct !DIGlobalVariable(name: "__log_const_area_size", scope: !2, file: !3, line: 323, type: !13, isLocal: false, isDefinition: true)
!510 = !DIGlobalVariableExpression(var: !511, expr: !DIExpression())
!511 = distinct !DIGlobalVariable(name: "__shell_area_size", scope: !2, file: !3, line: 324, type: !13, isLocal: false, isDefinition: true)
!512 = !DIGlobalVariableExpression(var: !513, expr: !DIExpression())
!513 = distinct !DIGlobalVariable(name: "__shell_root_cmds_area_size", scope: !2, file: !3, line: 325, type: !13, isLocal: false, isDefinition: true)
!514 = !DIGlobalVariableExpression(var: !515, expr: !DIExpression())
!515 = distinct !DIGlobalVariable(name: "__shell_subcmds_area_size", scope: !2, file: !3, line: 326, type: !13, isLocal: false, isDefinition: true)
!516 = !DIGlobalVariableExpression(var: !517, expr: !DIExpression())
!517 = distinct !DIGlobalVariable(name: "__shell_dynamic_subcmds_area_size", scope: !2, file: !3, line: 327, type: !13, isLocal: false, isDefinition: true)
!518 = !DIGlobalVariableExpression(var: !519, expr: !DIExpression())
!519 = distinct !DIGlobalVariable(name: "__cfb_font_area_size", scope: !2, file: !3, line: 328, type: !13, isLocal: false, isDefinition: true)
!520 = !DIGlobalVariableExpression(var: !521, expr: !DIExpression())
!521 = distinct !DIGlobalVariable(name: "__tracing_backend_area_size", scope: !2, file: !3, line: 329, type: !13, isLocal: false, isDefinition: true)
!522 = !DIGlobalVariableExpression(var: !523, expr: !DIExpression())
!523 = distinct !DIGlobalVariable(name: "___static_thread_data_area_size", scope: !2, file: !3, line: 330, type: !13, isLocal: false, isDefinition: true)
!524 = !DIGlobalVariableExpression(var: !525, expr: !DIExpression())
!525 = distinct !DIGlobalVariable(name: "__log_link_area_size", scope: !2, file: !3, line: 331, type: !13, isLocal: false, isDefinition: true)
!526 = !DIGlobalVariableExpression(var: !527, expr: !DIExpression())
!527 = distinct !DIGlobalVariable(name: "__log_backend_area_size", scope: !2, file: !3, line: 332, type: !13, isLocal: false, isDefinition: true)
!528 = !DIGlobalVariableExpression(var: !529, expr: !DIExpression())
!529 = distinct !DIGlobalVariable(name: "__log_dynamic_area_size", scope: !2, file: !3, line: 333, type: !13, isLocal: false, isDefinition: true)
!530 = !DIGlobalVariableExpression(var: !531, expr: !DIExpression())
!531 = distinct !DIGlobalVariable(name: "__k_timer_area_size", scope: !2, file: !3, line: 334, type: !13, isLocal: false, isDefinition: true)
!532 = !DIGlobalVariableExpression(var: !533, expr: !DIExpression())
!533 = distinct !DIGlobalVariable(name: "__k_mem_slab_area_size", scope: !2, file: !3, line: 335, type: !13, isLocal: false, isDefinition: true)
!534 = !DIGlobalVariableExpression(var: !535, expr: !DIExpression())
!535 = distinct !DIGlobalVariable(name: "__k_heap_area_size", scope: !2, file: !3, line: 336, type: !13, isLocal: false, isDefinition: true)
!536 = !DIGlobalVariableExpression(var: !537, expr: !DIExpression())
!537 = distinct !DIGlobalVariable(name: "__k_mutex_area_size", scope: !2, file: !3, line: 337, type: !13, isLocal: false, isDefinition: true)
!538 = !DIGlobalVariableExpression(var: !539, expr: !DIExpression())
!539 = distinct !DIGlobalVariable(name: "__k_stack_area_size", scope: !2, file: !3, line: 338, type: !13, isLocal: false, isDefinition: true)
!540 = !DIGlobalVariableExpression(var: !541, expr: !DIExpression())
!541 = distinct !DIGlobalVariable(name: "__k_msgq_area_size", scope: !2, file: !3, line: 339, type: !13, isLocal: false, isDefinition: true)
!542 = !DIGlobalVariableExpression(var: !543, expr: !DIExpression())
!543 = distinct !DIGlobalVariable(name: "__k_mbox_area_size", scope: !2, file: !3, line: 340, type: !13, isLocal: false, isDefinition: true)
!544 = !DIGlobalVariableExpression(var: !545, expr: !DIExpression())
!545 = distinct !DIGlobalVariable(name: "__k_pipe_area_size", scope: !2, file: !3, line: 341, type: !13, isLocal: false, isDefinition: true)
!546 = !DIGlobalVariableExpression(var: !547, expr: !DIExpression())
!547 = distinct !DIGlobalVariable(name: "__k_sem_area_size", scope: !2, file: !3, line: 342, type: !13, isLocal: false, isDefinition: true)
!548 = !DIGlobalVariableExpression(var: !549, expr: !DIExpression())
!549 = distinct !DIGlobalVariable(name: "__k_queue_area_size", scope: !2, file: !3, line: 343, type: !13, isLocal: false, isDefinition: true)
!550 = !DIGlobalVariableExpression(var: !551, expr: !DIExpression())
!551 = distinct !DIGlobalVariable(name: "__k_condvar_area_size", scope: !2, file: !3, line: 344, type: !13, isLocal: false, isDefinition: true)
!552 = !DIGlobalVariableExpression(var: !553, expr: !DIExpression())
!553 = distinct !DIGlobalVariable(name: "__k_event_area_size", scope: !2, file: !3, line: 345, type: !13, isLocal: false, isDefinition: true)
!554 = !DIGlobalVariableExpression(var: !555, expr: !DIExpression())
!555 = distinct !DIGlobalVariable(name: "__net_buf_pool_area_size", scope: !2, file: !3, line: 346, type: !13, isLocal: false, isDefinition: true)
!556 = !DIGlobalVariableExpression(var: !557, expr: !DIExpression())
!557 = distinct !DIGlobalVariable(name: "__log_mpsc_pbuf_area_size", scope: !2, file: !3, line: 347, type: !13, isLocal: false, isDefinition: true)
!558 = !DIGlobalVariableExpression(var: !559, expr: !DIExpression())
!559 = distinct !DIGlobalVariable(name: "__log_msg_ptr_area_size", scope: !2, file: !3, line: 348, type: !13, isLocal: false, isDefinition: true)
!560 = !DIGlobalVariableExpression(var: !561, expr: !DIExpression())
!561 = distinct !DIGlobalVariable(name: "__rom_region_size", scope: !2, file: !3, line: 349, type: !13, isLocal: false, isDefinition: true)
!562 = !DIGlobalVariableExpression(var: !563, expr: !DIExpression())
!563 = distinct !DIGlobalVariable(name: "__text_region_size", scope: !2, file: !3, line: 350, type: !13, isLocal: false, isDefinition: true)
!564 = !DIGlobalVariableExpression(var: !565, expr: !DIExpression())
!565 = distinct !DIGlobalVariable(name: "__rodata_region_size", scope: !2, file: !3, line: 351, type: !13, isLocal: false, isDefinition: true)
!566 = !DIGlobalVariableExpression(var: !567, expr: !DIExpression())
!567 = distinct !DIGlobalVariable(name: "__ram_region_size", scope: !2, file: !3, line: 352, type: !13, isLocal: false, isDefinition: true)
!568 = !DIGlobalVariableExpression(var: !569, expr: !DIExpression())
!569 = distinct !DIGlobalVariable(name: "__data_region_size", scope: !2, file: !3, line: 353, type: !13, isLocal: false, isDefinition: true)
!570 = !DIGlobalVariableExpression(var: !571, expr: !DIExpression())
!571 = distinct !DIGlobalVariable(name: "_ram_vector_start", scope: !2, file: !3, line: 357, type: !13, isLocal: false, isDefinition: true)
!572 = !DIGlobalVariableExpression(var: !573, expr: !DIExpression())
!573 = distinct !DIGlobalVariable(name: "__aeabi_ctype_table_", scope: !2, file: !3, line: 362, type: !574, isLocal: false, isDefinition: true)
!574 = !DICompositeType(tag: DW_TAG_array_type, baseType: !575, size: 2056, elements: !577)
!575 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !576)
!576 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!577 = !{!578}
!578 = !DISubrange(count: 257)
!579 = !{i32 1, !"NumRegisterParameters", i32 0}
!580 = !{i32 7, !"Dwarf Version", i32 5}
!581 = !{i32 2, !"Debug Info Version", i32 3}
!582 = !{i32 1, !"wchar_size", i32 4}
!583 = !{i32 8, !"PIC Level", i32 2}
!584 = !{i32 7, !"uwtable", i32 2}
!585 = !{i32 7, !"frame-pointer", i32 2}
!586 = !{!"Ubuntu clang version 17.0.4 (++20231031083134+309d55140c46-1~exp1~20231031083240.62)"}
!587 = distinct !DISubprogram(name: "readFromIntrinsicRetInt", scope: !3, file: !3, line: 7, type: !588, scopeLine: 7, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2)
!588 = !DISubroutineType(types: !589)
!589 = !{!8}
!590 = !DILocation(line: 8, column: 5, scope: !587)
!591 = distinct !DISubprogram(name: "z_arm_int_exit", scope: !3, file: !3, line: 12, type: !592, scopeLine: 12, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2)
!592 = !DISubroutineType(types: !593)
!593 = !{null}
!594 = !DILocation(line: 13, column: 5, scope: !591)
!595 = distinct !DISubprogram(name: "z_arm_fatal_error", scope: !3, file: !3, line: 16, type: !596, scopeLine: 16, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !601)
!596 = !DISubroutineType(types: !597)
!597 = !{null, !598, !599}
!598 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!599 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !600, size: 32)
!600 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!601 = !{}
!602 = !DILocalVariable(name: "reason", arg: 1, scope: !595, file: !3, line: 16, type: !598)
!603 = !DILocation(line: 16, column: 37, scope: !595)
!604 = !DILocalVariable(name: "esf", arg: 2, scope: !595, file: !3, line: 16, type: !599)
!605 = !DILocation(line: 16, column: 57, scope: !595)
!606 = !DILocation(line: 17, column: 5, scope: !595)
!607 = distinct !DISubprogram(name: "arch_cpu_atomic_idle", scope: !3, file: !3, line: 366, type: !608, scopeLine: 366, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !601)
!608 = !DISubroutineType(types: !609)
!609 = !{null, !598}
!610 = !DILocalVariable(name: "key", arg: 1, scope: !607, file: !3, line: 366, type: !598)
!611 = !DILocation(line: 366, column: 40, scope: !607)
!612 = !DILocation(line: 368, column: 1, scope: !607)
!613 = distinct !DISubprogram(name: "z_check_thread_stack_fail", scope: !3, file: !3, line: 370, type: !614, scopeLine: 370, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !601)
!614 = !DISubroutineType(types: !615)
!615 = !{null, !616}
!616 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !617, line: 96, baseType: !598)
!617 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "a48e64edacc5b19f56c99745232c963c")
!618 = !DILocalVariable(name: "addr", arg: 1, scope: !613, file: !3, line: 370, type: !616)
!619 = !DILocation(line: 370, column: 42, scope: !613)
!620 = !DILocation(line: 372, column: 1, scope: !613)
!621 = distinct !DISubprogram(name: "arch_cpu_idle", scope: !3, file: !3, line: 374, type: !592, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2)
!622 = !DILocation(line: 376, column: 1, scope: !621)
!623 = distinct !DISubprogram(name: "z_arm_cpu_idle_init", scope: !3, file: !3, line: 378, type: !592, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2)
!624 = !DILocation(line: 380, column: 1, scope: !623)
!625 = distinct !DISubprogram(name: "arch_switch_to_main_thread", scope: !3, file: !3, line: 382, type: !626, scopeLine: 383, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !601)
!626 = !DISubroutineType(types: !627)
!627 = !{null, !628, !628, !629, !8}
!628 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 32)
!629 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !630, line: 46, baseType: !598)
!630 = !DIFile(filename: "/usr/lib/llvm-17/lib/clang/17/include/stddef.h", directory: "", checksumkind: CSK_MD5, checksum: "d1776268f398bd1ca997c840ad581432")
!631 = !DILocalVariable(name: "main_thread", arg: 1, scope: !625, file: !3, line: 382, type: !628)
!632 = !DILocation(line: 382, column: 39, scope: !625)
!633 = !DILocalVariable(name: "stack", arg: 2, scope: !625, file: !3, line: 382, type: !628)
!634 = !DILocation(line: 382, column: 58, scope: !625)
!635 = !DILocalVariable(name: "stack_size", arg: 3, scope: !625, file: !3, line: 383, type: !629)
!636 = !DILocation(line: 383, column: 40, scope: !625)
!637 = !DILocalVariable(name: "_main", arg: 4, scope: !625, file: !3, line: 383, type: !8)
!638 = !DILocation(line: 383, column: 56, scope: !625)
!639 = !DILocation(line: 385, column: 1, scope: !625)
!640 = distinct !DISubprogram(name: "z_SysNmiOnReset", scope: !3, file: !3, line: 387, type: !608, scopeLine: 387, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !601)
!641 = !DILocalVariable(name: "reason", arg: 1, scope: !640, file: !3, line: 387, type: !598)
!642 = !DILocation(line: 387, column: 35, scope: !640)
!643 = !DILocation(line: 389, column: 1, scope: !640)
!644 = distinct !DISubprogram(name: "arch_new_thread", scope: !3, file: !3, line: 392, type: !645, scopeLine: 395, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !2, retainedNodes: !601)
!645 = !DISubroutineType(types: !646)
!646 = !{null, !628, !628, !629, !8, !628, !628, !628, !8, !598}
!647 = !DILocalVariable(name: "new_thread", arg: 1, scope: !644, file: !3, line: 392, type: !628)
!648 = !DILocation(line: 392, column: 28, scope: !644)
!649 = !DILocalVariable(name: "stack", arg: 2, scope: !644, file: !3, line: 392, type: !628)
!650 = !DILocation(line: 392, column: 46, scope: !644)
!651 = !DILocalVariable(name: "stack_size", arg: 3, scope: !644, file: !3, line: 393, type: !629)
!652 = !DILocation(line: 393, column: 32, scope: !644)
!653 = !DILocalVariable(name: "entry", arg: 4, scope: !644, file: !3, line: 393, type: !8)
!654 = !DILocation(line: 393, column: 48, scope: !644)
!655 = !DILocalVariable(name: "p1", arg: 5, scope: !644, file: !3, line: 394, type: !628)
!656 = !DILocation(line: 394, column: 31, scope: !644)
!657 = !DILocalVariable(name: "p2", arg: 6, scope: !644, file: !3, line: 394, type: !628)
!658 = !DILocation(line: 394, column: 41, scope: !644)
!659 = !DILocalVariable(name: "p3", arg: 7, scope: !644, file: !3, line: 394, type: !628)
!660 = !DILocation(line: 394, column: 51, scope: !644)
!661 = !DILocalVariable(name: "prio", arg: 8, scope: !644, file: !3, line: 395, type: !8)
!662 = !DILocation(line: 395, column: 29, scope: !644)
!663 = !DILocalVariable(name: "options", arg: 9, scope: !644, file: !3, line: 395, type: !598)
!664 = !DILocation(line: 395, column: 48, scope: !644)
!665 = !DILocation(line: 397, column: 1, scope: !644)
